# Prepare data for REddyProc USTAR threshold detection

In [1]:
from pathlib import Path

import diive as dv
from diive.core.io.files import save_parquet, load_parquet
from diive.core.times.times import insert_timestamp

## Load data

In [2]:
SOURCEDIR = r"."
FILENAME = r"31.5_FluxProcessingChain_after-L3.2_NEE_QCF11.parquet"
FILEPATH = Path(SOURCEDIR) / FILENAME
print(f"Data will be loaded from the following file:\n{FILEPATH}")
maindf = load_parquet(filepath=FILEPATH)
maindf

Data will be loaded from the following file:
31.5_FluxProcessingChain_after-L3.2_NEE_QCF11.parquet
Loaded .parquet file 31.5_FluxProcessingChain_after-L3.2_NEE_QCF11.parquet (0.491 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2  BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O  BADM_INST_AVERAGING_INT  BADM_INST_HEIGHT_SA  ...  SC_SINGLE_gfRMED_L3.1  FLAG_SC_SINGLE_gfRMED_L3.1_ISFILLED  NEE_L3.1  NEE_L3.1_QCF  NEE_L3.1_QCF0  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HAMPELDTNT_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_ZSCOREDTNT_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST  SUM_L3.2_NEE_L3.1_HARDFLAGS  SUM_L3.2_NEE_L3.1_SOFTFLAGS  SUM_L3.2_NEE_L3.1_FLAGS  FLAG_L3.2_NEE_L3.1_QCF  NEE_L3.1_L3.2_QCF  NEE_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                               ...
2005-01-01 00:15:00  1008.03      1.19492  0.024191     1204.51         0.0                   1.0          37.0                                0.0                                0.0                             -5.0                             -5.0                                33.0                                33.0                     30.0                 47.0  ...                7.33281                                  0.0  49.14921           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          4.0                          0.0                      4.0                     2.0                NaN                 NaN
2005-01-01 00:45:00  1008.11      1.19419  0.024204     1203.88         0.0                   1.0          37.0                                0.0                                0.0                             -5.0                             -5.0                                33.0                                33.0                     30.0                 47.0  ...               -3.10760                                  0.0 -25.33890           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          4.0                          0.0                      4.0                     2.0                NaN                 NaN
2005-01-01 01:15:00  1008.17      1.19318  0.024223     1202.93         0.0                   1.0          37.0                                0.0                                NaN                             -5.0                              NaN                                33.0                                 NaN                     30.0                 47.0  ...               -2.23223                                  0.0 -11.74519           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          4.0                          0.0                      4.0                     2.0                NaN                 NaN
2005-01-01 01:45:00  1008.24      1.19202  0.024246     1201.84         0.0                   1.0          37.0                                0.0                                0.0                             -5.0                             -5.0                                33.0                                33.0                     30.0                 47.0  ...               -7.10435                                  0.0  -8.40406           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2005-01-01 02:15:00  1008.29      1.19110  0.024264     1200.97         0.0                   1.0          37.0                                0.0                                NaN                             -5.0                              NaN                                33.0                                 NaN                     30.0                 47.0  ...               -4.70487                                  0.0 -11.96211           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          2.0                          1.0                      3.0                     2.0                NaN                 NaN
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                              ...                              ...                                 ...                                 ...                      ...                  ...  ...                    ...                                  ...       ...           ...            ...                                         ...                                             ...                                             ...                                                ...                          ...                          ...                      ...                     ...                ...                 ...
2019-12-31 21:45:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                  NaN  ...                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2019-12-31 22:15:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                  NaN  ...                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2019-12-31 22:45:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                  NaN  ...                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2019-12-31 23:15:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                  NaN  ...                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2019-12-31 23:45:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                  NaN  ...                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN

[262944 rows x 364 columns]

In [3]:
df = insert_timestamp(data=maindf, convention="end", insert_as_first_col=True, set_as_index=True)
df

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2  BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O  BADM_INST_AVERAGING_INT  BADM_INST_HEIGHT_SA  ...  SC_SINGLE_gfRMED_L3.1  FLAG_SC_SINGLE_gfRMED_L3.1_ISFILLED  NEE_L3.1  NEE_L3.1_QCF  NEE_L3.1_QCF0  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HAMPELDTNT_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_ZSCOREDTNT_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST  SUM_L3.2_NEE_L3.1_HARDFLAGS  SUM_L3.2_NEE_L3.1_SOFTFLAGS  SUM_L3.2_NEE_L3.1_FLAGS  FLAG_L3.2_NEE_L3.1_QCF  NEE_L3.1_L3.2_QCF  NEE_L3.1_L3.2_QCF0
TIMESTAMP_END                                                                                                                                                                                                                                                                                                                                                                  ...
2005-01-01 00:30:00  1008.03      1.19492  0.024191     1204.51         0.0                   1.0          37.0                                0.0                                0.0                             -5.0                             -5.0                                33.0                                33.0                     30.0                 47.0  ...                7.33281                                  0.0  49.14921           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          4.0                          0.0                      4.0                     2.0                NaN                 NaN
2005-01-01 01:00:00  1008.11      1.19419  0.024204     1203.88         0.0                   1.0          37.0                                0.0                                0.0                             -5.0                             -5.0                                33.0                                33.0                     30.0                 47.0  ...               -3.10760                                  0.0 -25.33890           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          4.0                          0.0                      4.0                     2.0                NaN                 NaN
2005-01-01 01:30:00  1008.17      1.19318  0.024223     1202.93         0.0                   1.0          37.0                                0.0                                NaN                             -5.0                              NaN                                33.0                                 NaN                     30.0                 47.0  ...               -2.23223                                  0.0 -11.74519           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          4.0                          0.0                      4.0                     2.0                NaN                 NaN
2005-01-01 02:00:00  1008.24      1.19202  0.024246     1201.84         0.0                   1.0          37.0                                0.0                                0.0                             -5.0                             -5.0                                33.0                                33.0                     30.0                 47.0  ...               -7.10435                                  0.0  -8.40406           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2005-01-01 02:30:00  1008.29      1.19110  0.024264     1200.97         0.0                   1.0          37.0                                0.0                                NaN                             -5.0                              NaN                                33.0                                 NaN                     30.0                 47.0  ...               -4.70487                                  0.0 -11.96211           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          2.0                          1.0                      3.0                     2.0                NaN                 NaN
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                              ...                              ...                                 ...                                 ...                      ...                  ...  ...                    ...                                  ...       ...           ...            ...                                         ...                                             ...                                             ...                                                ...                          ...                          ...                      ...                     ...                ...                 ...
2019-12-31 22:00:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                  NaN  ...                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2019-12-31 22:30:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                  NaN  ...                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2019-12-31 23:00:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                  NaN  ...                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2019-12-31 23:30:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                  NaN  ...                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2020-01-01 00:00:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                  NaN  ...                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                                             0.0                                                0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN

[262944 rows x 364 columns]

## Subset

In [4]:
subsetcols = ["NEE_L3.1_L3.2_QCF", "USTAR", "SW_IN_T1_47_1_gfXG", "TA_T1_47_1_gfXG"]
subset = df[subsetcols].copy()
# subset = subset.dropna()
subset

                     NEE_L3.1_L3.2_QCF     USTAR  SW_IN_T1_47_1_gfXG  TA_T1_47_1_gfXG
TIMESTAMP_END
2005-01-01 00:30:00                NaN  0.388239                 0.0        -2.160000
2005-01-01 01:00:00                NaN  0.657366                 0.0        -2.010000
2005-01-01 01:30:00                NaN  0.520923                 0.0        -1.791000
2005-01-01 02:00:00                NaN  0.522629                 0.0        -1.539000
2005-01-01 02:30:00                NaN  0.447028                 0.0        -1.338000
...                                ...       ...                 ...              ...
2019-12-31 22:00:00                NaN       NaN                 0.0        -1.551372
2019-12-31 22:30:00                NaN       NaN                 0.0        -2.677289
2019-12-31 23:00:00                NaN       NaN                 0.0        -0.795444
2019-12-31 23:30:00                NaN       NaN                 0.0        -1.815406
2020-01-01 00:00:00                NaN       NaN                 0.0         0.067361

[262944 rows x 4 columns]

## Stats

In [5]:
display(subset.dropna())

                     NEE_L3.1_L3.2_QCF     USTAR  SW_IN_T1_47_1_gfXG  TA_T1_47_1_gfXG
TIMESTAMP_END
2005-01-01 09:00:00          -3.889562  0.255829           14.508859        -0.139000
2005-01-01 10:30:00          -1.496870  0.238320           37.834139         0.142000
2005-01-01 11:00:00           4.837290  0.336832          124.863062         0.262000
2005-01-01 11:30:00          -2.182856  0.336577          177.868174         0.721000
2005-01-01 12:30:00           3.840530  0.468734          232.139673         1.584000
...                                ...       ...                 ...              ...
2019-03-20 07:00:00          13.580840  0.988478           21.497255         1.772078
2019-03-20 08:30:00          -1.492930  0.957692          272.660709         2.077811
2019-03-20 11:30:00         -14.116506  1.114060          731.047682         5.876844
2019-03-20 12:00:00         -13.425987  1.018750          768.926149         6.439722
2019-03-20 13:00:00         -14.800700  0.721157          803.123779         7.664089

[118411 rows x 4 columns]

## Save data

In [6]:
subset.to_csv("31.7_SUBSET_NEE_QCF11_IRGA75_2005-2019.csv")