# Merge data: IRGA75 (no self-heating correction, 2005-2017, 2019)

# Imports

In [1]:
import importlib.metadata
import warnings
from datetime import datetime

import pandas as pd
from diive.core.io.filereader import search_files, MultiDataFileReader
from diive.core.io.files import save_parquet

# pd.options.display.width = None
# pd.options.display.max_columns = None
pd.set_option('display.max_rows', 3000)
pd.set_option('display.max_columns', 3000)
warnings.filterwarnings(action='ignore', category=FutureWarning)
warnings.filterwarnings(action='ignore', category=UserWarning)
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
version_diive = importlib.metadata.version("diive")
print(f"diive version: v{version_diive}")

diive version: v0.89.0

# Merge L1 results to parquet

In [2]:
# Search original files and store filepaths in list
SOURCEDIR = r"../0_data/IRGA75-Level-1_fluxnet_2004-2017+2019_noSHC/"
sourcefiles = search_files(searchdirs=SOURCEDIR, pattern='*')
sourcefiles

[WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2004_IRGA75_noSHC_eddypro_CH-LAE_2004_FR-20250716-170438_fluxnet_2025-07-17T055955_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2005_1+4_IRGA75_noSHC_eddypro_CH-LAE_2005_1+4_FR-20250716-172023_fluxnet_2025-07-17T081040_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2005_2_IRGA75_noSHC_eddypro_CH-LAE_2005_2_FR-20250719-213210_fluxnet_2025-07-19T223345_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2005_3_IRGA75_noSHC_eddypro_CH-LAE_2005_3_FR-20250719-213753_fluxnet_2025-07-20T005853_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2006_IRGA75_noSHC_eddypro_CH-LAE_2006_FR-20250717-125210_fluxnet_2025-07-18T060534_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2007_IRGA75_noSHC_eddypro_CH-LAE_2007_FR-20250717-125620_fluxnet_2025-07-18T064851_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2008_1+4_IRGA75_noSHC_eddypro_CH-LAE_2008_1+4_FR-20250721-172906_fluxnet_2025-07-22T091450_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2008_2+3_IRGA75_noSHC_eddypro_CH-LAE_2008_2+3_FR-20250721-173754_fluxnet_2025-07-21T213846_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2009_IRGA75_noSHC_eddypro_CH-LAE_2009_FR-20250717-131814_fluxnet_2025-07-18T072030_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2010_IRGA75_noSHC_eddypro_CH-LAE_2010_FR-20250717-132211_fluxnet_2025-07-18T070013_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2011_IRGA75_noSHC_eddypro_CH-LAE_2011_FR-20250717-142458_fluxnet_2025-07-18T085226_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2012_IRGA75_noSHC_eddypro_CH-LAE_2012_FR-20250717-143018_fluxnet_2025-07-18T080044_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2013_IRGA75_noSHC_eddypro_CH-LAE_2013_FR-20250717-172123_fluxnet_2025-07-18T125625_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2014_IRGA75_noSHC_eddypro_CH-LAE_2014_FR-20250717-172519_fluxnet_2025-07-18T133643_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2015_IRGA75_noSHC_eddypro_CH-LAE_2015_FR-20250717-173020_fluxnet_2025-07-18T125703_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2016_1_IRGA75_noSHC_eddypro_CH-LAE_2016_1_FR-20250719-211724_fluxnet_2025-07-19T214711_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2016_2+3_IRGA75_noSHC_eddypro_CH-LAE_IRGA75_2016_2+3_FR-20250723-163351_fluxnet_2025-07-24T152517_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2017_1+2_IRGA75_noSHC_eddypro_CH-LAE_IRGA75_2017_1+2_FR-20250719-210900_fluxnet_2025-07-20T181731_adv.csv'),
 WindowsPath('../0_data/IRGA75-Level-1_fluxnet_2005-2017+2019_noSHC/2019_3_IRGA75_noSHC_eddypro_CH-LAE_IRGA75_2019_3_FR-20250721-171220_fluxnet_2025-07-21T195328_adv.csv')]

In [3]:
# Read data from files to dataframe
d = MultiDataFileReader(filepaths=sourcefiles,
                        filetype='EDDYPRO-FLUXNET-CSV-30MIN',
                        output_middle_timestamp=True)
df = d.data_df
df

Reading file 2004_IRGA75_noSHC_eddypro_CH-LAE_2004_FR-20250716-170438_fluxnet_2025-07-17T055955_adv.csv ...
Reading file 2005_1+4_IRGA75_noSHC_eddypro_CH-LAE_2005_1+4_FR-20250716-172023_fluxnet_2025-07-17T081040_adv.csv ...
Reading file 2005_2_IRGA75_noSHC_eddypro_CH-LAE_2005_2_FR-20250719-213210_fluxnet_2025-07-19T223345_adv.csv ...
Reading file 2005_3_IRGA75_noSHC_eddypro_CH-LAE_2005_3_FR-20250719-213753_fluxnet_2025-07-20T005853_adv.csv ...
Reading file 2006_IRGA75_noSHC_eddypro_CH-LAE_2006_FR-20250717-125210_fluxnet_2025-07-18T060534_adv.csv ...
Reading file 2007_IRGA75_noSHC_eddypro_CH-LAE_2007_FR-20250717-125620_fluxnet_2025-07-18T064851_adv.csv ...
Reading file 2008_1+4_IRGA75_noSHC_eddypro_CH-LAE_2008_1+4_FR-20250721-172906_fluxnet_2025-07-22T091450_adv.csv ...
Reading file 2008_2+3_IRGA75_noSHC_eddypro_CH-LAE_2008_2+3_FR-20250721-173754_fluxnet_2025-07-21T213846_adv.csv ...
Reading file 2009_IRGA75_noSHC_eddypro_CH-LAE_2009_FR-20250717-131814_fluxnet_2025-07-18T072030_adv.csv ...
Reading file 2010_IRGA75_noSHC_eddypro_CH-LAE_2010_FR-20250717-132211_fluxnet_2025-07-18T070013_adv.csv ...
Reading file 2011_IRGA75_noSHC_eddypro_CH-LAE_2011_FR-20250717-142458_fluxnet_2025-07-18T085226_adv.csv ...
Reading file 2012_IRGA75_noSHC_eddypro_CH-LAE_2012_FR-20250717-143018_fluxnet_2025-07-18T080044_adv.csv ...
Reading file 2013_IRGA75_noSHC_eddypro_CH-LAE_2013_FR-20250717-172123_fluxnet_2025-07-18T125625_adv.csv ...
Reading file 2014_IRGA75_noSHC_eddypro_CH-LAE_2014_FR-20250717-172519_fluxnet_2025-07-18T133643_adv.csv ...
Reading file 2015_IRGA75_noSHC_eddypro_CH-LAE_2015_FR-20250717-173020_fluxnet_2025-07-18T125703_adv.csv ...
Reading file 2016_1_IRGA75_noSHC_eddypro_CH-LAE_2016_1_FR-20250719-211724_fluxnet_2025-07-19T214711_adv.csv ...
Reading file 2016_2+3_IRGA75_noSHC_eddypro_CH-LAE_IRGA75_2016_2+3_FR-20250723-163351_fluxnet_2025-07-24T152517_adv.csv ...
Reading file 2017_1+2_IRGA75_noSHC_eddypro_CH-LAE_IRGA75_2017_1+2_FR-20250719-210900_fluxnet_2025-07-20T181731_adv.csv ...
Reading file 2019_3_IRGA75_noSHC_eddypro_CH-LAE_IRGA75_2019_3_FR-20250721-171220_fluxnet_2025-07-21T195328_adv.csv ...

,AIR_CP,AIR_DENSITY,AIR_MV,AIR_RHO_CP,AOA_METHOD,AXES_ROTATION_METHOD,BADM_HEIGHTC,BADM_INSTPAIR_EASTWARD_SEP_GA_CH4,BADM_INSTPAIR_EASTWARD_SEP_GA_CO2,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_EASTWARD_SEP_GA_NONE,BADM_INSTPAIR_HEIGHT_SEP_GA_CH4,BADM_INSTPAIR_HEIGHT_SEP_GA_CO2,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_NONE,BADM_INSTPAIR_NORTHWARD_SEP_GA_CH4,BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_NONE,BADM_INST_AVERAGING_INT,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CH4,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_NONE,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CH4,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_NONE,BADM_INST_GA_CP_TUBE_LENGTH_GA_CH4,BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2,BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_NONE,BADM_INST_HEIGHT_SA,BADM_INST_MODEL_GA_CH4,BADM_INST_MODEL_GA_CO2,BADM_INST_MODEL_GA_H2O,BADM_INST_MODEL_GA_NONE,BADM_INST_MODEL_SA,BADM_INST_SAMPLING_INT,BADM_INST_SA_GILL_ALIGN,BADM_INST_SA_WIND_FORMAT,BADM_LOCATION_ELEV,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_SA_OFFSET_NORTH,BOWEN,BURBA_METHOD,CH4,CH4_ABSLIM_NREX,CH4_DIAG_NREX,CH4_KID,CH4_LGD,CH4_MEAS_KUR,CH4_MEAS_MEDIAN,CH4_MEAS_NONE_MEAS_COV,CH4_MEAS_P25,CH4_MEAS_P75,CH4_MEAS_SIGMA,CH4_MEAS_SKW,CH4_MEAS_TYPE,CH4_MIXING_RATIO,CH4_MOLAR_DENSITY,CH4_NR,CH4_NUM_SPIKES,CH4_SPIKE_NREX,CH4_TLAG_ACTUAL,CH4_TLAG_MAX,CH4_TLAG_MIN,CH4_TLAG_NOMINAL,CH4_TLAG_USED,CH4_VM97_TEST,CH4_ZCD,CO2,CO2_ABSLIM_NREX,CO2_DIAG_NREX,CO2_KID,CO2_LGD,CO2_MEAS_CH4_MEAS_COV,CO2_MEAS_H2O_MEAS_COV,CO2_MEAS_KUR,CO2_MEAS_MEDIAN,CO2_MEAS_NONE_MEAS_COV,CO2_MEAS_P25,CO2_MEAS_P75,CO2_MEAS_SIGMA,CO2_MEAS_SKW,CO2_MEAS_TYPE,CO2_MIXING_RATIO,CO2_MOLAR_DENSITY,CO2_NR,CO2_NUM_SPIKES,CO2_SPIKE_NREX,CO2_TLAG_ACTUAL,CO2_TLAG_MAX,CO2_TLAG_MIN,CO2_TLAG_NOMINAL,CO2_TLAG_USED,CO2_VM97_TEST,CO2_ZCD,CUSTOM_AGC_IRGA75_MEAN,CUSTOM_AIR_P_MEAN,CUSTOM_AIR_P_MEAN_1,CUSTOM_AIR_P_MEAN_2,CUSTOM_AIR_T_MEAN,CUSTOM_CELL_T_MEAN,CUSTOM_CO2_MEAN_1,CUSTOM_CO2_MEAN_2,CUSTOM_COOLER_V_IRGA72_MEAN,CUSTOM_COOLER_V_IRGA75_MEAN,CUSTOM_DATA_SIZE_IRGA72_MEAN,CUSTOM_DATA_SIZE_IRGA75_MEAN,CUSTOM_FILTER_NR,CUSTOM_FILTER_NREX,CUSTOM_FLOW_VOLRATE_MEAN,CUSTOM_GA_DIAG_CODE_IRGA72_MEAN,CUSTOM_GA_DIAG_CODE_IRGA75_MEAN,CUSTOM_H2O_MEAN_1,CUSTOM_H2O_MEAN_2,CUSTOM_INT_P_MEAN,CUSTOM_SIGNAL_STRENGTH_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA75_MEAN,DENTRENDING_TIME_CONSTANT,DETRENDING_METHOD,DISPLACEMENT_HEIGHT,DOY_END,DOY_START,DRYAIR_DENSITY,DRYAIR_MV,DRYAIR_PARTIAL_PRESSURE,ET,ET_CORRDIFF,ET_RANDUNC_HF,ET_SCF,ET_SSITC_TEST,ET_STAGE1,ET_STAGE2,ET_UNCORR,EXPECT_NR,FC,FCH4,FCH4_CORRDIFF,FCH4_NR,FCH4_NSR,FCH4_RANDUNC_HF,FCH4_SCF,FCH4_SS,FCH4_SSITC_TEST,FCH4_SS_TEST,FCH4_STAGE1,FCH4_STAGE2,FCH4_UNCORR,FCH4_VADV,FC_CORRDIFF,FC_NR,FC_NSR,FC_RANDUNC_HF,FC_SCF,FC_SS,FC_SSITC_TEST,FC_SS_TEST,FC_STAGE1,FC_STAGE2,FC_UNCORR,FC_VADV,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FETCH_MAX,FETCH_OFFSET,FH2O,FH2O_CELL_CH4,FH2O_CELL_CO2,FH2O_CELL_NONE,FH2O_CORRDIFF,FH2O_NSR,FH2O_RANDUNC_HF,FH2O_SCF,FH2O_SS,FH2O_SSITC_TEST,FH2O_SS_TEST,FH2O_STAGE1,FH2O_STAGE2,FH2O_UNCORR,FH2O_VADV,FILENAME_HF,FILE_NR,FILE_TIME_DURATION,FNONE,FNONE_CORRDIFF,FNONE_NR,FNONE_NSR,FNONE_RANDUNC_HF,FNONE_SCF,FNONE_SS,FNONE_SSITC_TEST,FNONE_SS_TEST,FNONE_STAGE1,FNONE_STAGE2,FNONE_UNCORR,FNONE_VADV,FOOTPRINT_MODEL,H,H2O,H2O_ABSLIM_NREX,H2O_DIAG_NREX,H2O_KID,H2O_LGD,H2O_MEAS_CH4_MEAS_COV,H2O_MEAS_KUR,H2O_MEAS_MEDIAN,H2O_MEAS_NONE_MEAS_COV,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_TYPE,H2O_MIXING_RATIO,H2O_MOLAR_DENSITY,H2O_NR,H2O_NUM_SPIKES,H2O_SPIKE_NREX,H2O_TLAG_ACTUAL,H2O_TLAG_MAX,H2O_TLAG_MIN,H2O_TLAG_NOMINAL,H2O_TLAG_USED,H2O_VM97_TEST,H2O_ZCD,HPATH_GA_CH4,HPATH_GA_CO2,HPATH_GA_H2O,HPATH_GA_NONE,HPATH_SA,H_BU_BOT,H_BU_SPAR,H_BU_TOP,H_CELL_CH4,H_CELL_CO2,H_CELL_H2O,H_CELL_NONE,H_CORRDIFF,H_NR,H_NSR,H_RANDUNC_HF,H_SCF,H_SS,H_SSITC_TEST,H_SS_TEST,H_STAGE1,H_STAGE2,H_UNCORR,INST_LI7200_AGC_OR_RSSI,INST_LI7200_AUX_IN,INST_LI7200_CHOPPER,INST_LI7200_DELTA_P,INST_LI7200_DETECTOR,INST_LI7200_HEAD_DETECT,INST_LI7200_PLL,INST_LI7200_SYNC,INST_LI7200_T_IN,INST_LI7200_T_OUT,INST_LI7500_AGC_OR_RSSI,INST_LI7500_CHOPPER,INST_LI7500_DETECTOR,INST_LI7500_PLL,INST_LI7500_SYNC,INST_LI7700_BAD_AUX_TC1,INST_LI7700_BAD_AUX_TC2,INST_LI7700_BAD_AUX_TC3,INST_LI7700_BAD_TEMP,INST_LI7700_BLOCK_T_UNREG,INST_LI7700_BOTTOM_HEATER_ON,INST_LI7700_BOX_CONNECTED,INST_LI7700_CALIBRATING,INST_LI7700_LASER_T_UNREG,INST_LI7700_MOTOR_FAILURE,INST_LI7700_MOTOR_SPINNING,INST_LI7700_NOT_READY,INST_LI7700_NO_SIGNAL,INST_LI7700_PUMP_ON,INST_LI7700_RE_UNLOCKED,INST_LI7700_RSSI,INST_LI7700_TOP_HEATER_ON,KRYPTON_HYDRO_KH2O_GA_H2O,KRYPTON_HYDRO_KO2_GA_H2O,LE,LE_CORRDIFF,LE_NR,LE_RANDUNC_HF,LE_SCF,LE_SSITC_TEST,LE_STAGE1,LE_STAGE2,LE_UNCORR,LOGGER_SWVER_MAJOR,LOGGER_SWVER_MINOR,LOGGER_SWVER_REVISION,LW_IN_1_1_1,MANUFACTURER_GA_CH4,MANUFACTURER_GA_CO2,MANUFACTURER_GA_H2O,MANUFACTURER_GA_NONE,MANUFACTURER_SA,MO_LENGTH,MO_LENGTH_UNCORR,MV_AIR_CELL_CH4,MV_AIR_CELL_CO2,MV_AIR_CELL_H2O,MV_AIR_CELL_NONE,NIGHT,NONE,NONE_ABSLIM_NREX,NONE_DIAG_NREX,NONE_KID,NONE_LGD,NONE_MEAS_KUR,NONE_MEAS_MEDIAN,NONE_MEAS_P25,NONE_MEAS_P75,NONE_MEAS_SIGMA,NONE_MEAS_SKW,NONE_MEAS_TYPE,NONE_MIXING_RATIO,NONE_MOLAR_DENSITY,NONE_NR,NONE_NUM_SPIKES,NONE_SPIKE_NREX,NONE_TLAG_ACTUAL,NONE_TLAG_MAX,NONE_TLAG_MIN,NONE_TLAG_NOMINAL,NONE_TLAG_USED,NONE_VM97_TEST,NONE_ZCD,NUM_BIOMET_VARS,NUM_CUSTOM_VARS,PA_1_1_1,PA_CELL,PA_EP,PPFD_IN_1_1_1,RESPONSE_TIME_GA_CH4,RESPONSE_TIME_GA_CO2,RESPONSE_TIME_GA_H2O,RESPONSE_TIME_GA_NONE,RESPONSE_TIME_SA,RH_1_1_1,RH_EP,ROT_PITCH,ROT_ROLL,ROT_YAW,ROUGHNESS_LENGTH,SCH4_SINGLE,SC_SINGLE,SET_SINGLE,SH2O_SINGLE,SH_SINGLE,SLE_SINGLE,SNONE_SINGLE,SONIC_DIAG_NREX,SONIC_NR,SPECIFIC_HEAT_EVAP,SPECIFIC_HUMIDITY,SPECTRAL_CORRECTION_METHOD,SPEC_CORR_LI7700_A,SPEC_CORR_LI7700_B,SPEC_CORR_LI7700_C,SW_IN_1_1_1,SW_IN_POT,TAU,TAU_CORRDIFF,TAU_NR,TAU_NSR,TAU_RANDUNC_HF,TAU_SCF,TAU_SS,TAU_SSITC_TEST,TAU_SS_TEST,TAU_STAGE1,TAU_STAGE2,TAU_UNCORR,TA_1_1_1,TA_EP,TDEW,TIMELAG_DETECTION_METHOD,TIMESTAMP_START,TKE,TSTAR,T_CELL,T_SONIC,T_SONIC_ABSLIM_NREX,T_SONIC_ITC,T_SONIC_ITC_TEST,T_SONIC_KID,T_SONIC_KUR,T_SONIC_LGD,T_SONIC_MEDIAN,T_SONIC_NR,T_SONIC_NUM_SPIKES,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_SPIKE_NREX,T_SONIC_VM97_TEST,T_SONIC_ZCD,U,USTAR,USTAR_UNCORR,U_ABSLIM_NREX,U_ITC,U_ITC_TEST,U_KID,U_KUR,U_LGD,U_MEDIAN,U_NUM_SPIKES,U_P25,U_P75,U_SIGMA,U_SKW,U_SPIKE_NREX,U_UNROT,U_VM97_TEST,U_ZCD,V,VAPOR_DENSITY,VAPOR_DRYAIR_RATIO,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VM97_AOA_HF,VM97_NSHW_HF,VM97_TLAG_HF,VM97_TLAG_SF,VPATH_GA_CH4,VPATH_GA_CO2,VPATH_GA_H2O,VPATH_GA_NONE,VPATH_SA,VPD_EP,V_ABSLIM_NREX,V_KID,V_KUR,V_LGD,V_MEDIAN,V_NUM_SPIKES,V_P25,V_P75,V_SIGMA,V_SKW,V_SPIKE_NREX,V_UNROT,V_VM97_TEST,V_ZCD,W,WBOOST_APPLIED,WD,WD_FILTER_NR,WD_FILTER_NREX,WD_SIGMA,WPL_APPLIED,WS,WS_MAX,W_ABSLIM_NREX,W_CH4_MEAS_COV,W_CO2_MEAS_COV,W_H2O_MEAS_COV,W_ITC,W_ITC_TEST,W_KID,W_KUR,W_LGD,W_MEDIAN,W_NONE_MEAS_COV,W_NUM_SPIKES,W_P25,W_P75,W_SIGMA,W_SKW,W_SPIKE_NREX,W_T_SONIC_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N0004,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N1626,W_UNROT,W_U_COV,W_VM97_TEST,W_ZCD,ZL,ZL_UNCORR
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2004-03-30 14:45:00,1005.41,1.12844,0.025668,1134.55,0.0,1.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.0,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,689.0,47.4783,8.36439,209.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,6.0,NaN,NaN,NaN,NaN,NaN,801001111.0,NaN,50.0035,92175.8,NaN,NaN,291.446,NaN,NaN,NaN,NaN,1.6883,NaN,2.69689,36000.0,0.0,NaN,NaN,248.001,NaN,NaN,NaN,NaN,NaN,190.69,0.0,0.0,24.79,90.6248,90.6040,1.12844,0.025668,93.1361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.3195,40.6379,61.9754,86.9213,104.023,130.224,47.5417,-7.21463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,360.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,484.2770,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,801001111.0,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.020265,36000.0,0.633340,71.12790,1.03229,8.0,0.0,1.0,469.1280,469.1280,469.1280,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-17.6228,-16.9308,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,NaN,93.1361,93.1361,NaN,NaN,NaN,NaN,NaN,0.02,NaN,NaN,-10.393400,NaN,255.032,5.55,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,36000.0,2466030.0,NaN,2.0,NaN,NaN,NaN,NaN,804.3650,-0.248116,0.020929,36000.0,2.097330,0.125806,1.04906,18.0,1.0,2.0,-0.248116,-0.248116,-0.236513,NaN,14.39040,NaN,2.0,2.004033e+11,2.933770,0.910293,14.39040,14.3904,0.0,27.0,2.0,34.16820,2.80312,0.0,14.28,36000.0,2.0,13.95,14.79,0.598003,0.582705,4.0,800000001.0,6695.0,1.25861,0.468909,0.457814,0.0,36.0,3.0,10.55620,2.44031,0.00,1.33346,3.0,0.255112,2.20081,1.250800,-0.079848,6.0,-0.319741,800000000.0,14.0,-2.097000e-13,NaN,NaN,NaN,16.34550,81.0,81.0,81100.0,81100.0,NaN,NaN,NaN,NaN,12.5,NaN,0.0,9.67526,2.73612,0.00,0.097368,2.0,-1.131460,1.123260,1.738060,-0.049581,3.0,-1.195950,800000000.0,105.0,2.347030e-14,0.0,140.2270,36000.0,0.0,66.8951,1.0,1.25861,6.90358,0.0,NaN,NaN,NaN,23.0,2.0,10.50620,2.70522,0.00,0.031505,NaN,0.0,-0.802545,0.862113,1.132340,-0.183047,0.0,0.413493,0.430109,0.227067,0.302449,0.357852,0.392181,0.411335,0.421176,0.426057,0.428443,0.429576,-0.227060,-0.209191,800000001.0,14.0,-1.260300,-1.311810
2004-03-30 15:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-03-30 15:45:00,1005.42,1.12663,0.025709,1132.74,0.0,1.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.0,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,689.0,47.4783,8.36439,209.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00000,36000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200.00,0.0,0.0,24.79,90.6665,90.6457,1.12663,0.025709,93.1361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0043,59.7740,91.1591,127.8520,153.006,191.546,69.9287,-10.61200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,360.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,236.1910,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.002408,36000.0,1.704530,34.72550,1.02464,11.0,0.0,1.0,230.5120,230.5120,230.5120,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-63.3936,-61.4854,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,NaN,93.1361,93.1361,NaN,NaN,NaN,NaN,NaN,0.02,NaN,NaN,-2.061840,NaN,283.762,5.55,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,36000.0,2464940.0,NaN,2.0,NaN,NaN,NaN,NaN,633.1080,0.360343,0.002520,36000.0,1.136880,0.079574,1.03728,20.0,1.0,2.0,0.360343,0.360343,0.347392,NaN,14.85160,NaN,2.0,2.004033e+11,1.271540,0.368693,14.85160,14.8516,0.0,16.0,2.0,45.55650,3.86126,0.0,14.81,36000.0,4.0,14.61,15.07,0.393687,0.445787,7.0,800000001.0,10330.0,1.75180,0.565546,0.555290,0.0,53.0,4.0,7.19170,3.19249,0.00,1.74152,0.0,1.063450,2.38781,0.952038,0.270380,0.0,0.416462,800000000.0,39.0,1.298230e-13,NaN,NaN,NaN,16.83960,81.0,80.0,80000.0,80000.0,NaN,NaN,NaN,NaN,12.5,NaN,0.0,8.60571,3.31903,0.00,-0.057621,1.0,-0.651132,0.534932,0.958030,0.410680,2.0,-1.700410,800000000.0,210.0,6.276300e-14,0.0,105.0050,36000.0,0.0,34.1989,1.0,1.75180,5.81501,0.0,NaN,NaN,NaN,2.0,1.0,8.72020,2.68872,0.00,0.016758,NaN,0.0,-0.578768,0.624265,0.847874,-0.134105,0.0,0.203499,0.208674,0.118395,0.150023,0.173974,0.189719,0.199146,0.204235,0.206710,0.207852,0.208402,-0.063026,0.002830,800000001.0,39.0,-0.350351,-0.361224
2004-03-30 16:15:00,1005.43,1.12587,0.025726,1131.98,0.0,1.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.0,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,689.0,47.4783,8.36439,209.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00000,36000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200.00,0.0,0.0,24.79,90.6873,90.6665,1.12587,0.025726,93.1361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.8720,56.9544,86.8590,121.8210,145.789,182.510,66.6301,-10.11140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,360.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,139.5710,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.023290,36000.0,0.858901,24.03770,1.02290,8.0,0.0,1.0,136.4460,136.4460,136.4460,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-75.1012,-73.0019,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,NaN,93.1361,93.1361,NaN,NaN,NaN,NaN,NaN,0.02,NaN,NaN,-0.851707,NaN,260.626,5.55,NaN,NaN,NaN,NaN,5.75167,NaN,NaN,0.0,36000.0,2464470.0,NaN,2.0,NaN,NaN,NaN,NaN,532.2040,-0.283909,0.001396,36000.0,1.324420,0.054830,1.03459,23.0,1.0,2.0,-0.283909,-0.283909,-0.274418,NaN,15.04620,NaN,2.0,2.004033e+11,1.016360,0.245534,15.04620,15.0462,0.0,8.0,1.0,33.85540,5.21449,0.0,14.95,36000.0,53.0,14.86,15.15,0.301643,1.398810,96.0,800000111.0,12733.0,1.91436,0.502164,0.493699,0.0,50.0,3.0,7.76922,2.79636,0.00,1.95646,2.0,1.361780,2.57337,0.866820,-0.334730,4.0,-0.311764,800000000.0,76.0,-2.201720e-13,NaN,NaN,NaN,17.05190,81.0,81.0,80000.0,80000.0,NaN,NaN,NaN,NaN,12.5,NaN,0.0,8.16130,2.74307,0.00,-0.037033,2.0,-0.569254,0.561891,0.800071,0.136002,4.0,-1.888590,800000000.0,360.0,8.788510e-14,0.0,126.4780,36000.0,0.0,30.2754,1.0,1.91436,4.65570,0.0,NaN,NaN,NaN,6.0,1.0,9.08741,2.97192,0.00,0.031907,NaN,0.0,-0.522040,0.546954,0.800765,-0.227967,0.0,0.120537,0.130810,0.072154,0.093746,0.109357,0.119172,0.124815,0.127802,0.129396,0.130245,0.130654,-0.028456,-0.034904,800000000.0,76.0,-0.295734,-0.304238

# Remove vars with zero records

In [4]:
stats = df.describe().T

In [5]:
# Find available variables that have more than 0 records, remove all others from data
available_vars = stats.loc[stats['count'] > 0].index
not_available_vars = stats.loc[stats['count'] == 0].index
print("No records for the following vars:")
print(stats.loc[not_available_vars])

No records for the following vars:
                                        count  mean  std  min  25%  50%  75%  max
BADM_INSTPAIR_EASTWARD_SEP_GA_CH4         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_EASTWARD_SEP_GA_NONE        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_HEIGHT_SEP_GA_CH4           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_HEIGHT_SEP_GA_NONE          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_NORTHWARD_SEP_GA_CH4        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_NORTHWARD_SEP_GA_NONE       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CH4     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_NONE    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CH4       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_IN_DIAM_GA_NONE      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_LENGTH_GA_CH4        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_LENGTH_GA_NONE       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_GA_CH4                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_GA_CO2                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_GA_H2O                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_GA_NONE                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_SA                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_SA_GILL_ALIGN                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_SA_WIND_FORMAT                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4                                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_ABSLIM_NREX                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_DIAG_NREX                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_KID                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_LGD                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MEAS_KUR                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MEAS_MEDIAN                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MEAS_NONE_MEAS_COV                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MEAS_P25                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MEAS_P75                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MEAS_SIGMA                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MEAS_SKW                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MEAS_TYPE                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MIXING_RATIO                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_MOLAR_DENSITY                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_NR                                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_NUM_SPIKES                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_SPIKE_NREX                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_TLAG_ACTUAL                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_TLAG_MAX                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_TLAG_MIN                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_TLAG_NOMINAL                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_TLAG_USED                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_VM97_TEST                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CH4_ZCD                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_CH4_MEAS_COV                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_NONE_MEAS_COV                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4                                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_CORRDIFF                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_NR                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_NSR                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_RANDUNC_HF                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_SCF                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_SS                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_SSITC_TEST                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_SS_TEST                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_STAGE1                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_STAGE2                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_UNCORR                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FCH4_VADV                                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FH2O_CELL_CH4                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FH2O_CELL_CO2                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FH2O_CELL_NONE                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FILENAME_HF                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE                                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_CORRDIFF                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_NR                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_NSR                                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_RANDUNC_HF                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_SCF                                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_SS                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_SSITC_TEST                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_SS_TEST                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_STAGE1                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_STAGE2                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_UNCORR                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FNONE_VADV                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H2O_MEAS_CH4_MEAS_COV                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H2O_MEAS_NONE_MEAS_COV                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
HPATH_GA_CH4                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
HPATH_GA_NONE                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_BU_BOT                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_BU_SPAR                                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_BU_TOP                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_CELL_CH4                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_CELL_CO2                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_CELL_H2O                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_CELL_NONE                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_AUX_IN                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_CHOPPER                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_DELTA_P                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_DETECTOR                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_HEAD_DETECT                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_PLL                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_SYNC                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_T_IN                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_T_OUT                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7500_CHOPPER                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7500_DETECTOR                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7500_PLL                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7500_SYNC                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BAD_AUX_TC1                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BAD_AUX_TC2                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BAD_AUX_TC3                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BAD_TEMP                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BLOCK_T_UNREG                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BOTTOM_HEATER_ON              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BOX_CONNECTED                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_CALIBRATING                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_LASER_T_UNREG                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_MOTOR_FAILURE                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_MOTOR_SPINNING                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_NOT_READY                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_NO_SIGNAL                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_PUMP_ON                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_RE_UNLOCKED                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_RSSI                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_TOP_HEATER_ON                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
KRYPTON_HYDRO_KH2O_GA_H2O                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
KRYPTON_HYDRO_KO2_GA_H2O                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
LOGGER_SWVER_MAJOR                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
LOGGER_SWVER_MINOR                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
LOGGER_SWVER_REVISION                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_GA_CH4                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_GA_CO2                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_GA_H2O                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_GA_NONE                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_SA                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MV_AIR_CELL_CH4                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MV_AIR_CELL_CO2                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MV_AIR_CELL_H2O                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MV_AIR_CELL_NONE                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE                                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_ABSLIM_NREX                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_DIAG_NREX                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_KID                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_LGD                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MEAS_KUR                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MEAS_MEDIAN                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MEAS_P25                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MEAS_P75                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MEAS_SIGMA                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MEAS_SKW                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MEAS_TYPE                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MIXING_RATIO                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_MOLAR_DENSITY                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_NR                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_NUM_SPIKES                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_SPIKE_NREX                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_TLAG_ACTUAL                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_TLAG_MAX                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_TLAG_MIN                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_TLAG_NOMINAL                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_TLAG_USED                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_VM97_TEST                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
NONE_ZCD                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
RESPONSE_TIME_GA_CH4                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
RESPONSE_TIME_GA_NONE                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
ROT_ROLL                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SCH4_SINGLE                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SNONE_SINGLE                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SPEC_CORR_LI7700_A                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SPEC_CORR_LI7700_B                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SPEC_CORR_LI7700_C                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
VPATH_GA_CH4                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
VPATH_GA_NONE                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
W_CH4_MEAS_COV                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
W_NONE_MEAS_COV                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [6]:
print("Removing variables with 0 records ...")
df_available = df[available_vars].copy()

print(f"Variables removed:")
df_not_available = df[not_available_vars].copy()
_list = df_not_available.columns.tolist()
for c in _list:
    print(c, end=" ")

Removing variables with 0 records ...
Variables removed:
BADM_INSTPAIR_EASTWARD_SEP_GA_CH4 BADM_INSTPAIR_EASTWARD_SEP_GA_NONE BADM_INSTPAIR_HEIGHT_SEP_GA_CH4 BADM_INSTPAIR_HEIGHT_SEP_GA_NONE BADM_INSTPAIR_NORTHWARD_SEP_GA_CH4 BADM_INSTPAIR_NORTHWARD_SEP_GA_NONE BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CH4 BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2 BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_NONE BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CH4 BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2 BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O BADM_INST_GA_CP_TUBE_IN_DIAM_GA_NONE BADM_INST_GA_CP_TUBE_LENGTH_GA_CH4 BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2 BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O BADM_INST_GA_CP_TUBE_LENGTH_GA_NONE BADM_INST_MODEL_GA_CH4 BADM_INST_MODEL_GA_CO2 BADM_INST_MODEL_GA_H2O BADM_INST_MODEL_GA_NONE BADM_INST_MODEL_SA BADM_INST_SA_GILL_ALIGN BADM_INST_SA_WIND_FORMAT CH4 CH4_ABSLIM_NREX CH4_DIAG_NREX CH4_KID CH4_LGD CH4_MEAS_KUR CH4_MEAS_MEDIAN CH4_MEAS_NONE_MEAS_COV CH4_MEAS_P25 CH4_MEAS_P75 CH4_MEAS_SIGMA CH4_MEAS_SKW CH4_MEAS_TYPE CH4_MIXING_RATIO CH4_MOLAR_DENSITY CH4_NR CH4_NUM_SPIKES CH4_SPIKE_NREX CH4_TLAG_ACTUAL CH4_TLAG_MAX CH4_TLAG_MIN CH4_TLAG_NOMINAL CH4_TLAG_USED CH4_VM97_TEST CH4_ZCD CO2_MEAS_CH4_MEAS_COV CO2_MEAS_NONE_MEAS_COV FCH4 FCH4_CORRDIFF FCH4_NR FCH4_NSR FCH4_RANDUNC_HF FCH4_SCF FCH4_SS FCH4_SSITC_TEST FCH4_SS_TEST FCH4_STAGE1 FCH4_STAGE2 FCH4_UNCORR FCH4_VADV FH2O_CELL_CH4 FH2O_CELL_CO2 FH2O_CELL_NONE FILENAME_HF FNONE FNONE_CORRDIFF FNONE_NR FNONE_NSR FNONE_RANDUNC_HF FNONE_SCF FNONE_SS FNONE_SSITC_TEST FNONE_SS_TEST FNONE_STAGE1 FNONE_STAGE2 FNONE_UNCORR FNONE_VADV H2O_MEAS_CH4_MEAS_COV H2O_MEAS_NONE_MEAS_COV HPATH_GA_CH4 HPATH_GA_NONE H_BU_BOT H_BU_SPAR H_BU_TOP H_CELL_CH4 H_CELL_CO2 H_CELL_H2O H_CELL_NONE INST_LI7200_AUX_IN INST_LI7200_CHOPPER INST_LI7200_DELTA_P INST_LI7200_DETECTOR INST_LI7200_HEAD_DETECT INST_LI7200_PLL INST_LI7200_SYNC INST_LI7200_T_IN INST_LI7200_T_OUT INST_LI7500_CHOPPER INST_LI7500_DETECTOR INST_LI7500_PLL INST_LI7500_SYNC INST_LI7700_BAD_AUX_TC1 INST_LI7700_BAD_AUX_TC2 INST_LI7700_BAD_AUX_TC3 INST_LI7700_BAD_TEMP INST_LI7700_BLOCK_T_UNREG INST_LI7700_BOTTOM_HEATER_ON INST_LI7700_BOX_CONNECTED INST_LI7700_CALIBRATING INST_LI7700_LASER_T_UNREG INST_LI7700_MOTOR_FAILURE INST_LI7700_MOTOR_SPINNING INST_LI7700_NOT_READY INST_LI7700_NO_SIGNAL INST_LI7700_PUMP_ON INST_LI7700_RE_UNLOCKED INST_LI7700_RSSI INST_LI7700_TOP_HEATER_ON KRYPTON_HYDRO_KH2O_GA_H2O KRYPTON_HYDRO_KO2_GA_H2O LOGGER_SWVER_MAJOR LOGGER_SWVER_MINOR LOGGER_SWVER_REVISION MANUFACTURER_GA_CH4 MANUFACTURER_GA_CO2 MANUFACTURER_GA_H2O MANUFACTURER_GA_NONE MANUFACTURER_SA MV_AIR_CELL_CH4 MV_AIR_CELL_CO2 MV_AIR_CELL_H2O MV_AIR_CELL_NONE NONE NONE_ABSLIM_NREX NONE_DIAG_NREX NONE_KID NONE_LGD NONE_MEAS_KUR NONE_MEAS_MEDIAN NONE_MEAS_P25 NONE_MEAS_P75 NONE_MEAS_SIGMA NONE_MEAS_SKW NONE_MEAS_TYPE NONE_MIXING_RATIO NONE_MOLAR_DENSITY NONE_NR NONE_NUM_SPIKES NONE_SPIKE_NREX NONE_TLAG_ACTUAL NONE_TLAG_MAX NONE_TLAG_MIN NONE_TLAG_NOMINAL NONE_TLAG_USED NONE_VM97_TEST NONE_ZCD RESPONSE_TIME_GA_CH4 RESPONSE_TIME_GA_NONE ROT_ROLL SCH4_SINGLE SNONE_SINGLE SPEC_CORR_LI7700_A SPEC_CORR_LI7700_B SPEC_CORR_LI7700_C VPATH_GA_CH4 VPATH_GA_NONE W_CH4_MEAS_COV W_NONE_MEAS_COV

# Remove meteo variables from EC L1 output
- EddyPro seems to output only meteo data for time periods when fluxes were available
- the fill meteo data will be added in subsequent notebooks

In [7]:
removecols = [v for v in df_available.columns if str(v).endswith("_1_1_1")]
print("The following variables will be removed from EC results:")
print(removecols)

The following variables will be removed from EC results:
['LW_IN_1_1_1', 'PA_1_1_1', 'PPFD_IN_1_1_1', 'RH_1_1_1', 'SW_IN_1_1_1', 'TA_1_1_1']

In [8]:
# Remove meteo data from flux results because this meteo has gaps after flux processing
keepcols = []
[keepcols.append(c) for c in df_available.columns if "_1_1_1" not in c]
df_reduced = df_available[keepcols].copy()
df_reduced

,AIR_CP,AIR_DENSITY,AIR_MV,AIR_RHO_CP,AOA_METHOD,AXES_ROTATION_METHOD,BADM_HEIGHTC,BADM_INSTPAIR_EASTWARD_SEP_GA_CO2,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_CO2,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INST_AVERAGING_INT,BADM_INST_HEIGHT_SA,BADM_INST_SAMPLING_INT,BADM_LOCATION_ELEV,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_SA_OFFSET_NORTH,BOWEN,BURBA_METHOD,CO2,CO2_ABSLIM_NREX,CO2_DIAG_NREX,CO2_KID,CO2_LGD,CO2_MEAS_H2O_MEAS_COV,CO2_MEAS_KUR,CO2_MEAS_MEDIAN,CO2_MEAS_P25,CO2_MEAS_P75,CO2_MEAS_SIGMA,CO2_MEAS_SKW,CO2_MEAS_TYPE,CO2_MIXING_RATIO,CO2_MOLAR_DENSITY,CO2_NR,CO2_NUM_SPIKES,CO2_SPIKE_NREX,CO2_TLAG_ACTUAL,CO2_TLAG_MAX,CO2_TLAG_MIN,CO2_TLAG_NOMINAL,CO2_TLAG_USED,CO2_VM97_TEST,CO2_ZCD,CUSTOM_AGC_IRGA75_MEAN,CUSTOM_AIR_P_MEAN,CUSTOM_AIR_P_MEAN_1,CUSTOM_AIR_P_MEAN_2,CUSTOM_AIR_T_MEAN,CUSTOM_CELL_T_MEAN,CUSTOM_CO2_MEAN_1,CUSTOM_CO2_MEAN_2,CUSTOM_COOLER_V_IRGA72_MEAN,CUSTOM_COOLER_V_IRGA75_MEAN,CUSTOM_DATA_SIZE_IRGA72_MEAN,CUSTOM_DATA_SIZE_IRGA75_MEAN,CUSTOM_FILTER_NR,CUSTOM_FILTER_NREX,CUSTOM_FLOW_VOLRATE_MEAN,CUSTOM_GA_DIAG_CODE_IRGA72_MEAN,CUSTOM_GA_DIAG_CODE_IRGA75_MEAN,CUSTOM_H2O_MEAN_1,CUSTOM_H2O_MEAN_2,CUSTOM_INT_P_MEAN,CUSTOM_SIGNAL_STRENGTH_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA75_MEAN,DENTRENDING_TIME_CONSTANT,DETRENDING_METHOD,DISPLACEMENT_HEIGHT,DOY_END,DOY_START,DRYAIR_DENSITY,DRYAIR_MV,DRYAIR_PARTIAL_PRESSURE,ET,ET_CORRDIFF,ET_RANDUNC_HF,ET_SCF,ET_SSITC_TEST,ET_STAGE1,ET_STAGE2,ET_UNCORR,EXPECT_NR,FC,FC_CORRDIFF,FC_NR,FC_NSR,FC_RANDUNC_HF,FC_SCF,FC_SS,FC_SSITC_TEST,FC_SS_TEST,FC_STAGE1,FC_STAGE2,FC_UNCORR,FC_VADV,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FETCH_MAX,FETCH_OFFSET,FH2O,FH2O_CORRDIFF,FH2O_NSR,FH2O_RANDUNC_HF,FH2O_SCF,FH2O_SS,FH2O_SSITC_TEST,FH2O_SS_TEST,FH2O_STAGE1,FH2O_STAGE2,FH2O_UNCORR,FH2O_VADV,FILE_NR,FILE_TIME_DURATION,FOOTPRINT_MODEL,H,H2O,H2O_ABSLIM_NREX,H2O_DIAG_NREX,H2O_KID,H2O_LGD,H2O_MEAS_KUR,H2O_MEAS_MEDIAN,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_TYPE,H2O_MIXING_RATIO,H2O_MOLAR_DENSITY,H2O_NR,H2O_NUM_SPIKES,H2O_SPIKE_NREX,H2O_TLAG_ACTUAL,H2O_TLAG_MAX,H2O_TLAG_MIN,H2O_TLAG_NOMINAL,H2O_TLAG_USED,H2O_VM97_TEST,H2O_ZCD,HPATH_GA_CO2,HPATH_GA_H2O,HPATH_SA,H_CORRDIFF,H_NR,H_NSR,H_RANDUNC_HF,H_SCF,H_SS,H_SSITC_TEST,H_SS_TEST,H_STAGE1,H_STAGE2,H_UNCORR,INST_LI7200_AGC_OR_RSSI,INST_LI7500_AGC_OR_RSSI,LE,LE_CORRDIFF,LE_NR,LE_RANDUNC_HF,LE_SCF,LE_SSITC_TEST,LE_STAGE1,LE_STAGE2,LE_UNCORR,MO_LENGTH,MO_LENGTH_UNCORR,NIGHT,NUM_BIOMET_VARS,NUM_CUSTOM_VARS,PA_CELL,PA_EP,RESPONSE_TIME_GA_CO2,RESPONSE_TIME_GA_H2O,RESPONSE_TIME_SA,RH_EP,ROT_PITCH,ROT_YAW,ROUGHNESS_LENGTH,SC_SINGLE,SET_SINGLE,SH2O_SINGLE,SH_SINGLE,SLE_SINGLE,SONIC_DIAG_NREX,SONIC_NR,SPECIFIC_HEAT_EVAP,SPECIFIC_HUMIDITY,SPECTRAL_CORRECTION_METHOD,SW_IN_POT,TAU,TAU_CORRDIFF,TAU_NR,TAU_NSR,TAU_RANDUNC_HF,TAU_SCF,TAU_SS,TAU_SSITC_TEST,TAU_SS_TEST,TAU_STAGE1,TAU_STAGE2,TAU_UNCORR,TA_EP,TDEW,TIMELAG_DETECTION_METHOD,TIMESTAMP_START,TKE,TSTAR,T_CELL,T_SONIC,T_SONIC_ABSLIM_NREX,T_SONIC_ITC,T_SONIC_ITC_TEST,T_SONIC_KID,T_SONIC_KUR,T_SONIC_LGD,T_SONIC_MEDIAN,T_SONIC_NR,T_SONIC_NUM_SPIKES,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_SPIKE_NREX,T_SONIC_VM97_TEST,T_SONIC_ZCD,U,USTAR,USTAR_UNCORR,U_ABSLIM_NREX,U_ITC,U_ITC_TEST,U_KID,U_KUR,U_LGD,U_MEDIAN,U_NUM_SPIKES,U_P25,U_P75,U_SIGMA,U_SKW,U_SPIKE_NREX,U_UNROT,U_VM97_TEST,U_ZCD,V,VAPOR_DENSITY,VAPOR_DRYAIR_RATIO,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VM97_AOA_HF,VM97_NSHW_HF,VM97_TLAG_HF,VM97_TLAG_SF,VPATH_GA_CO2,VPATH_GA_H2O,VPATH_SA,VPD_EP,V_ABSLIM_NREX,V_KID,V_KUR,V_LGD,V_MEDIAN,V_NUM_SPIKES,V_P25,V_P75,V_SIGMA,V_SKW,V_SPIKE_NREX,V_UNROT,V_VM97_TEST,V_ZCD,W,WBOOST_APPLIED,WD,WD_FILTER_NR,WD_FILTER_NREX,WD_SIGMA,WPL_APPLIED,WS,WS_MAX,W_ABSLIM_NREX,W_CO2_MEAS_COV,W_H2O_MEAS_COV,W_ITC,W_ITC_TEST,W_KID,W_KUR,W_LGD,W_MEDIAN,W_NUM_SPIKES,W_P25,W_P75,W_SIGMA,W_SKW,W_SPIKE_NREX,W_T_SONIC_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N0004,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N1626,W_UNROT,W_U_COV,W_VM97_TEST,W_ZCD,ZL,ZL_UNCORR
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2004-03-30 14:45:00,1005.41,1.12844,0.025668,1134.55,0.0,1.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,30.0,47.0,20.0,689.0,47.4783,8.36439,209.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,6.0,NaN,NaN,NaN,NaN,NaN,801001111.0,NaN,50.0035,92175.8,NaN,NaN,291.446,NaN,NaN,NaN,NaN,1.6883,NaN,2.69689,36000.0,0.0,NaN,NaN,248.001,NaN,NaN,NaN,NaN,NaN,190.69,0.0,0.0,24.79,90.6248,90.6040,1.12844,0.025668,93.1361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.3195,40.6379,61.9754,86.9213,104.023,130.224,47.5417,-7.21463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,360.0,0.0,484.2770,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,801001111.0,NaN,NaN,NaN,11.0,0.020265,36000.0,0.633340,71.12790,1.03229,8.0,0.0,1.0,469.1280,469.1280,469.1280,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-17.6228,-16.9308,0.0,6.0,7.0,93.1361,93.1361,NaN,NaN,0.02,NaN,-10.393400,255.032,5.55,NaN,0.000000,NaN,NaN,NaN,0.0,36000.0,2466030.0,NaN,2.0,804.3650,-0.248116,0.020929,36000.0,2.097330,0.125806,1.04906,18.0,1.0,2.0,-0.248116,-0.248116,-0.236513,14.39040,NaN,2.0,2.004033e+11,2.933770,0.910293,14.39040,14.3904,0.0,27.0,2.0,34.16820,2.80312,0.0,14.28,36000.0,2.0,13.95,14.79,0.598003,0.582705,4.0,800000001.0,6695.0,1.25861,0.468909,0.457814,0.0,36.0,3.0,10.55620,2.44031,0.00,1.33346,3.0,0.255112,2.20081,1.250800,-0.079848,6.0,-0.319741,800000000.0,14.0,-2.097000e-13,NaN,NaN,NaN,16.34550,81.0,81.0,81100.0,81100.0,NaN,NaN,12.5,NaN,0.0,9.67526,2.73612,0.00,0.097368,2.0,-1.131460,1.123260,1.738060,-0.049581,3.0,-1.195950,800000000.0,105.0,2.347030e-14,0.0,140.2270,36000.0,0.0,66.8951,1.0,1.25861,6.90358,0.0,NaN,NaN,23.0,2.0,10.50620,2.70522,0.00,0.031505,0.0,-0.802545,0.862113,1.132340,-0.183047,0.0,0.413493,0.430109,0.227067,0.302449,0.357852,0.392181,0.411335,0.421176,0.426057,0.428443,0.429576,-0.227060,-0.209191,800000001.0,14.0,-1.260300,-1.311810
2004-03-30 15:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-03-30 15:45:00,1005.42,1.12663,0.025709,1132.74,0.0,1.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,30.0,47.0,20.0,689.0,47.4783,8.36439,209.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00000,36000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200.00,0.0,0.0,24.79,90.6665,90.6457,1.12663,0.025709,93.1361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0043,59.7740,91.1591,127.8520,153.006,191.546,69.9287,-10.61200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,360.0,0.0,236.1910,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,NaN,NaN,11.0,0.002408,36000.0,1.704530,34.72550,1.02464,11.0,0.0,1.0,230.5120,230.5120,230.5120,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-63.3936,-61.4854,0.0,6.0,7.0,93.1361,93.1361,NaN,NaN,0.02,NaN,-2.061840,283.762,5.55,NaN,0.000000,NaN,NaN,NaN,0.0,36000.0,2464940.0,NaN,2.0,633.1080,0.360343,0.002520,36000.0,1.136880,0.079574,1.03728,20.0,1.0,2.0,0.360343,0.360343,0.347392,14.85160,NaN,2.0,2.004033e+11,1.271540,0.368693,14.85160,14.8516,0.0,16.0,2.0,45.55650,3.86126,0.0,14.81,36000.0,4.0,14.61,15.07,0.393687,0.445787,7.0,800000001.0,10330.0,1.75180,0.565546,0.555290,0.0,53.0,4.0,7.19170,3.19249,0.00,1.74152,0.0,1.063450,2.38781,0.952038,0.270380,0.0,0.416462,800000000.0,39.0,1.298230e-13,NaN,NaN,NaN,16.83960,81.0,80.0,80000.0,80000.0,NaN,NaN,12.5,NaN,0.0,8.60571,3.31903,0.00,-0.057621,1.0,-0.651132,0.534932,0.958030,0.410680,2.0,-1.700410,800000000.0,210.0,6.276300e-14,0.0,105.0050,36000.0,0.0,34.1989,1.0,1.75180,5.81501,0.0,NaN,NaN,2.0,1.0,8.72020,2.68872,0.00,0.016758,0.0,-0.578768,0.624265,0.847874,-0.134105,0.0,0.203499,0.208674,0.118395,0.150023,0.173974,0.189719,0.199146,0.204235,0.206710,0.207852,0.208402,-0.063026,0.002830,800000001.0,39.0,-0.350351,-0.361224
2004-03-30 16:15:00,1005.43,1.12587,0.025726,1131.98,0.0,1.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,30.0,47.0,20.0,689.0,47.4783,8.36439,209.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00000,36000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200.00,0.0,0.0,24.79,90.6873,90.6665,1.12587,0.025726,93.1361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.8720,56.9544,86.8590,121.8210,145.789,182.510,66.6301,-10.11140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,360.0,0.0,139.5710,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,NaN,NaN,11.0,0.023290,36000.0,0.858901,24.03770,1.02290,8.0,0.0,1.0,136.4460,136.4460,136.4460,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-75.1012,-73.0019,0.0,6.0,7.0,93.1361,93.1361,NaN,NaN,0.02,NaN,-0.851707,260.626,5.55,NaN,NaN,NaN,5.75167,NaN,0.0,36000.0,2464470.0,NaN,2.0,532.2040,-0.283909,0.001396,36000.0,1.324420,0.054830,1.03459,23.0,1.0,2.0,-0.283909,-0.283909,-0.274418,15.04620,NaN,2.0,2.004033e+11,1.016360,0.245534,15.04620,15.0462,0.0,8.0,1.0,33.85540,5.21449,0.0,14.95,36000.0,53.0,14.86,15.15,0.301643,1.398810,96.0,800000111.0,12733.0,1.91436,0.502164,0.493699,0.0,50.0,3.0,7.76922,2.79636,0.00,1.95646,2.0,1.361780,2.57337,0.866820,-0.334730,4.0,-0.311764,800000000.0,76.0,-2.201720e-13,NaN,NaN,NaN,17.05190,81.0,81.0,80000.0,80000.0,NaN,NaN,12.5,NaN,0.0,8.16130,2.74307,0.00,-0.037033,2.0,-0.569254,0.561891,0.800071,0.136002,4.0,-1.888590,800000000.0,360.0,8.788510e-14,0.0,126.4780,36000.0,0.0,30.2754,1.0,1.91436,4.65570,0.0,NaN,NaN,6.0,1.0,9.08741,2.97192,0.00,0.031907,0.0,-0.522040,0.546954,0.800765,-0.227967,0.0,0.120537,0.130810,0.072154,0.093746,0.109357,0.119172,0.124815,0.127802,0.129396,0.130245,0.130654,-0.028456,-0.034904,800000000.0,76.0,-0.295734,-0.304238
2004-03-30 16:45:00,1005.44,1.12521,0.025742,1131.33,0.0,1.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,30.0,47.0,20.0,689.0,47.4783,8.36439,209.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00000,36000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200.00,0.0,0.0,24.79,90.7082,90.6873,1.12521,0.025742,93.1361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.3262,55.5954,84.7864,118.9140,142.310,178.155,65.0402,-9.87010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,360.0,0.0,107.7410,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,NaN,NaN,11.0,0.055845,36000.0,0.830733,15.23010,1.03015,35.0,1.0,3.0,104.5870,104.5870,104.5870,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-31.6216,-30.4594,0.0,6.0,7.0,93.1361,93.1361,NaN,NaN,0.02,NaN,15.727600,229.030,5.55,NaN,NaN,NaN,4.96311,NaN,0.0,36000.0,2464080.0,NaN,2.0,423.3620,-0.134134,0.014357,36000.0,1.947160,0.015183,1.04579,15.0,1.0,1.0,-0.134134,-0.134134,-0.128261,15.21420,NaN,2.0,2.004033e+11,0.457230,0.275829,15.21420,15.2142,0.0,22.0,2.0,28.29780,2.53448,0.0,15.16,36000.0,10.0,15.02,15.38,0.229770,0.631922,18.0,800000011.0,16553.0,1.36902,0.345264,0.337621,0.0,55.0,4.0,6.80122,2.84120,0.00,1.40964,2.0,1.015290,1.75994,0.593376,-0.275427,4.0,-0.864011,800000000.0,247.0,-9.712440e-14,NaN,NaN,NaN,17.23720,81.0,80.0,80000.0,80000.0,NaN,NaN,12.5,NaN,0.0,9.87520,3.06468,0.00,0.012318,0.0,-0.300372,0.344458,0.493785,-0.230485,0.0,-0.994978,800000000.0,855.0,1.240730e-13,0.0,159.5110,36000.0,0.0,30.8068,1.0,1.36902,3.50954,0.0,NaN,NaN,4.0,1.0,12.33380,2.38278,0.00,-0.074076,0.0,-0.429920,0.430717,0.564395,0.231812,0.0,0.092446,0.090983,0.056832,0.071401,0.080399,0.085194,0.087909,0.089473,0.090311,0.090723,0.090910,0.371090,-0.012976,800000000.0,247.0,-0.702368,-0.729167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-03-20 16:45:00,1007.86,1.16459,0.024826,1173.74,0.0,1.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,30.0,47.0,20.0,689.0,47.4783,8.36439,209.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801011100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.00000,36000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,24.79,79.7082,79.6873,1.16114,0.024945,93.9592,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.2461,60.3762,92.0776,129.1400,154.548,193.475,70.6333,-10.71890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,360.0,0.0,140.5610,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,NaN,NaN,11.0,0.021954,36000.0,1.591250,24.10370,1.02069,0.0,0.0,1.0,137.7110,137.7110,137.7110,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-152.0190,-148.1930,0.0,6.0,7.0,94.4081,94.4081,NaN,NaN,0.02,39.8535,10.204300,276.140,5.55,NaN,1.624220,25.06510,5.41305,1119.870,0.0,36000.0,2479370.0,0.002963,2.0,349.9040,-0.468915,0.007943,36000.0,0.959985,0.098074,1.03112,16.0,0.0,2.0,-0.468915,-0.468915,-0.454762,8.76184,-4.17104,2.0,2.019032e+11,1.645230,0.188726,8.76184,12.6729,0.0,0.0,1.0,24.92490,2.60823,0.0,12.66,36000.0,2.0,12.46,12.89,0.301869,0.112297,2.0,800000001.0,8784.0,2.16683,0.634542,0.624893,0.0,20.0,2.0,9.46826,2.52014,0.00,2.12704,8.0,1.201820,3.02605,1.239040,0.234685,14.0,0.228083,800000000.0,20.0,-1.076680e-13,0.003450,0.002972,4.48905,11.26390,81.0,80.0,80000.0,80000.0,NaN,NaN,12.5,6.77483,0.0,10.01340,3.71158,0.00,0.037812,1.0,-0.612912,0.592784,0.931335,-0.323051,1.0,-2.120320,800000000.0,166.0,-3.852650e-14,0.0,113.2270,36000.0,0.0,33.6580,1.0,2.16683,6.96549,0.0,NaN,NaN,17.0,2.0,9.64299,2.84874,0.00,0.032191,2.0,-0.673061,0.670298,0.942269,-0.023800,4.0,0.117327,0.121649,0.042471,0.064819,0.085650,0.100864,0.110510,0.116021,0.119008,0.120584,0.121349,0.383872,-0.350438,800000000.0,20.0,-0.146100,-0.149872
2019-03-20 17:15:00,1007.73,1.16718,0.024773,1176.20,0.0,1.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,30.0,47.0,20.0,689.0,47.4783,8.36439,209.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801011100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.00000,36000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,24.79,79.7290,79.7082,1.16388,0.024886,93.9894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.7253,56.5892,86.3022,121.0400,144.854,181.340,66.2029,-10.04650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000.0,360.0,0.0,106.8270,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,801001100.0,NaN,NaN,NaN,11.0,0.004754,36000.0,1.562790,20.05610,1.01757,3.0,0.0,1.0,104.9830,104.9830,104.9830,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-181.1030,-177.2830,0.0,6.0,7.0,94.4174,94.4174,NaN,NaN,0.02,39.5048,9.354350,277.355,5.55,NaN,3.227320,49.80430,-17.64860,2226.390,0.0,36000.0,2480730.0,0.002824,2.0,233.9850,-0.439827,0.019922,36000.0,1.377610,0.109687,1.02616,4.0,0.0,1.0,-0.439827,-0.439827,-0.428616,8.18719,-4.80423,2.0,2.019032e+11,2.022740,0.147955,8.18719,12.8064,0.0,4.0,1.0,20.54500,2.72386,0.0,12.79,36000.0,10.0,12.65,12.97,0.237499,0.173033,19.0,800000011.0,10214.0,2.65242,0.613864,0.605990,0.0,7.0,2.0,7.22939,2.38230,0.00,2.55125,14.0,1.627490,3.68322,1.401190,0.141421,23.0,0.335038,800000000.0,13.0,8.679580e-14,0.003296,0.002832,4.27973,10.83340,81.0,81.0,80000.0,80000.0,NaN,NaN,12.5,6.55371,0.0,6.78554,3.56708,0.00,0.013342,0.0,-0.658931,0.621130,1.049000,-0.040046,0.0,-2.595620,800000000.0,109.0,-3.476670e-14,0.0,110.5470,36000.0,0.0,29.7126,1.0,2.65242,7.30215,0.0,NaN,NaN,27.0,2.0,8.29332,3.38968,0.00,-0.005610,0.0,-0.631538,0.666318,0.990832,-0.125209,0.0,0.089256,0.092566,0.040154,0.056648,0.070131,0.079327,0.085203,0.088672,0.090686,0.091788,0.092332,0.431124,-0.339284,800000000.0,13.0,-0.122638,-0.125280

# Save to file

In [9]:
OUTNAME = "21.2_FLUXES_IRGA75_L1_noSHC_2004-2017_2019"
filepath = save_parquet(filename=OUTNAME, data=df_reduced)
# df_reduced.to_csv(f"{OUTNAME}.csv")

Saved file 21.2_FLUXES_IRGA75_L1_noSHC_2005-2017_2019.parquet (4.105 seconds).

# **End of notebook**.

In [10]:
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2025-08-29 12:40:38