# Prepare data for REddyProc USTAR threshold detection

In [1]:
from datetime import datetime
from pathlib import Path

import diive as dv
from diive.core.io.files import save_parquet, load_parquet
from diive.core.times.times import insert_timestamp

## Load data

In [2]:
SOURCEDIR = r"."
FILENAME = r"12_IRGA72_FluxProcessingChain_after-L3.2_NEE_QCF11_2016-2024.parquet"
FILEPATH = Path(SOURCEDIR) / FILENAME
print(f"Data will be loaded from the following file:\n{FILEPATH}")
maindf = load_parquet(filepath=FILEPATH)
maindf

Data will be loaded from the following file:
11_IRGA72_FluxProcessingChain_after-L3.2_NEE_QCF11_2016-2024.parquet
Loaded .parquet file 11_IRGA72_FluxProcessingChain_after-L3.2_NEE_QCF11_2016-2024.parquet (0.326 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2  BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O  BADM_INST_AVERAGING_INT  BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2  ...  FC_L2_QCF  FC_L2_QCF0  SC_SINGLE_gfRMED_L3.1  FLAG_SC_SINGLE_gfRMED_L3.1_ISFILLED  NEE_L3.1  NEE_L3.1_QCF  NEE_L3.1_QCF0  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HAMPELDTNT_TEST  SUM_L3.2_NEE_L3.1_HARDFLAGS  SUM_L3.2_NEE_L3.1_SOFTFLAGS  SUM_L3.2_NEE_L3.1_FLAGS  FLAG_L3.2_NEE_L3.1_QCF  NEE_L3.1_L3.2_QCF  NEE_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2016-01-01 00:15:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                                    NaN  ...        NaN         NaN                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2016-01-01 00:45:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                                    NaN  ...        NaN         NaN                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2016-01-01 01:15:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                                    NaN  ...        NaN         NaN                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2016-01-01 01:45:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                                    NaN  ...        NaN         NaN                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2016-01-01 02:15:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                                    NaN  ...        NaN         NaN                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                              ...                              ...                                 ...                                 ...                      ...                                    ...  ...        ...         ...                    ...                                  ...       ...           ...            ...                                         ...                                             ...                          ...                          ...                      ...                     ...                ...                 ...
2024-12-31 21:45:00  1008.09      1.20135  0.024060     1211.07         0.0                   1.0          37.0                                1.0                                1.0                             -1.0                             -1.0                                11.0                                11.0                     30.0                                   12.0  ...   -2.79421         NaN                4.53740                                  0.0   1.74319       1.74319            NaN                                         0.0                                             0.0                          0.0                          1.0                      1.0                     1.0            1.74319                 NaN
2024-12-31 22:15:00  1008.14      1.20010  0.024085     1209.87         0.0                   1.0          37.0                                1.0                                1.0                             -1.0                             -1.0                                11.0                                11.0                     30.0                                   12.0  ...   -9.03663    -9.03663               -1.57778                                  0.0 -10.61441     -10.61441      -10.61441                                         0.0                                             2.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2024-12-31 22:45:00  1008.20      1.20023  0.024081     1210.07         0.0                   1.0          37.0                                1.0                                1.0                             -1.0                             -1.0                                11.0                                11.0                     30.0                                   12.0  ...   -6.75955         NaN                1.65862                                  0.0  -5.10093      -5.10093            NaN                                         0.0                                             2.0                          2.0                          1.0                      3.0                     2.0                NaN                 NaN
2024-12-31 23:15:00  1008.19      1.19504  0.024186     1204.83         0.0                   1.0          37.0                                1.0                                1.0                             -1.0                             -1.0                                11.0                                11.0                     30.0                                   12.0  ...  -16.89140         NaN               -3.83563                                  0.0 -20.72703     -20.72703            NaN                                         0.0                                             2.0                          2.0                          1.0                      3.0                     2.0                NaN                 NaN
2024-12-31 23:45:00  1008.15      1.20042  0.024078     1210.20         0.0                   1.0          37.0                                1.0                                1.0                             -1.0                             -1.0                                11.0                                11.0                     30.0                                   12.0  ...        NaN         NaN                5.81585                                  0.0   6.90444           NaN            NaN                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN

[157824 rows x 369 columns]

In [3]:
df = insert_timestamp(data=maindf, convention="end", insert_as_first_col=True, set_as_index=True)
df

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2  BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O  BADM_INST_AVERAGING_INT  BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2  ...  FC_L2_QCF  FC_L2_QCF0  SC_SINGLE_gfRMED_L3.1  FLAG_SC_SINGLE_gfRMED_L3.1_ISFILLED  NEE_L3.1  NEE_L3.1_QCF  NEE_L3.1_QCF0  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HAMPELDTNT_TEST  SUM_L3.2_NEE_L3.1_HARDFLAGS  SUM_L3.2_NEE_L3.1_SOFTFLAGS  SUM_L3.2_NEE_L3.1_FLAGS  FLAG_L3.2_NEE_L3.1_QCF  NEE_L3.1_L3.2_QCF  NEE_L3.1_L3.2_QCF0
TIMESTAMP_END                                                                                                                                                                                                                                                                                                                                                                                    ...
2016-01-01 00:30:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                                    NaN  ...        NaN         NaN                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2016-01-01 01:00:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                                    NaN  ...        NaN         NaN                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2016-01-01 01:30:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                                    NaN  ...        NaN         NaN                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2016-01-01 02:00:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                                    NaN  ...        NaN         NaN                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2016-01-01 02:30:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                              NaN                              NaN                                 NaN                                 NaN                      NaN                                    NaN  ...        NaN         NaN                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                              ...                              ...                                 ...                                 ...                      ...                                    ...  ...        ...         ...                    ...                                  ...       ...           ...            ...                                         ...                                             ...                          ...                          ...                      ...                     ...                ...                 ...
2024-12-31 22:00:00  1008.09      1.20135  0.024060     1211.07         0.0                   1.0          37.0                                1.0                                1.0                             -1.0                             -1.0                                11.0                                11.0                     30.0                                   12.0  ...   -2.79421         NaN                4.53740                                  0.0   1.74319       1.74319            NaN                                         0.0                                             0.0                          0.0                          1.0                      1.0                     1.0            1.74319                 NaN
2024-12-31 22:30:00  1008.14      1.20010  0.024085     1209.87         0.0                   1.0          37.0                                1.0                                1.0                             -1.0                             -1.0                                11.0                                11.0                     30.0                                   12.0  ...   -9.03663    -9.03663               -1.57778                                  0.0 -10.61441     -10.61441      -10.61441                                         0.0                                             2.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2024-12-31 23:00:00  1008.20      1.20023  0.024081     1210.07         0.0                   1.0          37.0                                1.0                                1.0                             -1.0                             -1.0                                11.0                                11.0                     30.0                                   12.0  ...   -6.75955         NaN                1.65862                                  0.0  -5.10093      -5.10093            NaN                                         0.0                                             2.0                          2.0                          1.0                      3.0                     2.0                NaN                 NaN
2024-12-31 23:30:00  1008.19      1.19504  0.024186     1204.83         0.0                   1.0          37.0                                1.0                                1.0                             -1.0                             -1.0                                11.0                                11.0                     30.0                                   12.0  ...  -16.89140         NaN               -3.83563                                  0.0 -20.72703     -20.72703            NaN                                         0.0                                             2.0                          2.0                          1.0                      3.0                     2.0                NaN                 NaN
2025-01-01 00:00:00  1008.15      1.20042  0.024078     1210.20         0.0                   1.0          37.0                                1.0                                1.0                             -1.0                             -1.0                                11.0                                11.0                     30.0                                   12.0  ...        NaN         NaN                5.81585                                  0.0   6.90444           NaN            NaN                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN

[157824 rows x 369 columns]

## Subset

In [4]:
[print(c) for c in df.columns if "SIGMA" in c]

CO2_MEAS_SIGMA
H2O_MEAS_SIGMA
T_SONIC_SIGMA
U_SIGMA
V_SIGMA
WD_SIGMA
W_SIGMA

[None, None, None, None, None, None, None]

In [5]:
subsetcols = ["NEE_L3.1_L3.2_QCF", "USTAR", "SW_IN_T1_47_1_gfXG", "TA_T1_47_1_gfXG", "W_SIGMA"]
subset = df[subsetcols].copy()
# subset = subset.dropna()
subset

                     NEE_L3.1_L3.2_QCF     USTAR  SW_IN_T1_47_1_gfXG  TA_T1_47_1_gfXG   W_SIGMA
TIMESTAMP_END
2016-01-01 00:30:00                NaN       NaN                 0.0        -1.598717       NaN
2016-01-01 01:00:00                NaN       NaN                 0.0        -1.598717       NaN
2016-01-01 01:30:00                NaN       NaN                 0.0        -0.501368       NaN
2016-01-01 02:00:00                NaN       NaN                 0.0        -0.501368       NaN
2016-01-01 02:30:00                NaN       NaN                 0.0        -0.247269       NaN
...                                ...       ...                 ...              ...       ...
2024-12-31 22:00:00            1.74319  0.245203                 0.0        -0.504794  0.633562
2024-12-31 22:30:00                NaN  0.388421                 0.0        -0.296828  0.730129
2024-12-31 23:00:00                NaN  0.532218                 0.0        -0.392922  0.783631
2024-12-31 23:30:00                NaN  0.590691                 0.0         0.792661  1.105490
2025-01-01 00:00:00                NaN  0.460926                 0.0        -0.422600  0.905128

[157824 rows x 5 columns]

## Stats

In [6]:
display(subset.dropna())

                     NEE_L3.1_L3.2_QCF     USTAR  SW_IN_T1_47_1_gfXG  TA_T1_47_1_gfXG   W_SIGMA
TIMESTAMP_END
2016-01-22 12:30:00           3.510816  0.977617          388.521645        -0.656756  0.956033
2016-01-22 13:00:00           2.290646  1.108450          461.366255         0.840450  1.046980
2016-01-22 13:30:00           2.496543  1.037480          450.249060         1.379183  0.798401
2016-01-22 14:00:00           3.101360  0.967246          434.350843         2.005894  0.829359
2016-01-22 14:30:00           2.944462  0.716777          394.412050         2.176656  0.879129
...                                ...       ...                 ...              ...       ...
2024-12-31 19:30:00          -0.720610  0.173538            0.000000         0.084183  0.433117
2024-12-31 20:00:00          -0.492216  0.254667            0.000000        -0.054978  0.541555
2024-12-31 20:30:00          -2.661993  0.249883            0.000000         0.443217  0.484344
2024-12-31 21:00:00          -1.308400  0.144146            0.000000         0.833206  0.296022
2024-12-31 22:00:00           1.743190  0.245203            0.000000        -0.504794  0.633562

[102572 rows x 5 columns]

## Save data

In [7]:
filename = "14_IRGA72_SUBSET_NEE_QCF11_2016-2024"
subset.to_csv(f"{filename}.csv")
save_parquet(data=subset, filename=filename)

Saved file 13_SUBSET_NEE_QCF11_IRGA72_2016-2024.parquet (0.107 seconds).

'13_SUBSET_NEE_QCF11_IRGA72_2016-2024.parquet'

# **End of notebook**

---

Congratulations, you reached the end of this notebook! Before you go let's store your finish time.

In [8]:
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2025-11-13 10:55:47