# Wind direction checks L0 fluxes IRGA72 (2016-2026.09)

In [1]:
from datetime import datetime

from diive.corrections import WindDirOffset
from diive.plotting import HeatmapDateTime
from diive.core.io.files import load_parquet

In [2]:
# The merged Level-0 record written by 01_IRGA72-L0_merge_output_to_parquet_2016-2026.09. It lives in
# the external (untracked) data folder and is addressed by absolute path, so this notebook does not
# depend on the working directory.
SOURCEPATH = (r"F:\Sync\luhk_work\dev-data\datasets-data\dataset_ch-lae_flux_product-data"
              r"\workflow\00_L0_checks\IRGA72"
              r"\01_OPENLAG_EDDYPRO_FLUXNET_OUTPUT_IRGA72_2016-2026.09.parquet")
df = load_parquet(filepath=SOURCEPATH)
df

  > Loaded .parquet file
F:\Sync\luhk_work\dev-data\datasets-data\dataset_ch-lae_flux_product-data\workflow\00_L0_checks\IRGA
72\01_OPENLAG_EDDYPRO_FLUXNET_OUTPUT_IRGA72_2016-2026.09.parquet (4.892 seconds).

,AIR_MV,AIR_DENSITY,AIR_RHO_CP,AIR_CP,AOA_METHOD,AXES_ROTATION_METHOD,BOWEN,BURBA_METHOD,BADM_LOCATION_LAT,BADM_LOCATION_LONG,...,W_VM97_TEST,W_LGD,W_KID,W_ZCD,W_ITC,W_ITC_TEST,WBOOST_APPLIED,WPL_APPLIED,ZL,ZL_UNCORR
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,
2016-01-11 15:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-11 15:45:00,0.025415,1.13966,1145.77,1005.36,0.0,1.0,NaN,0.0,47.4783,8.36439,...,801010000.0,1.50,7.65689,0.0,4.0,1.0,0.0,0.0,0.009173,0.009198
2016-01-11 16:15:00,0.025509,1.13546,1141.57,1005.38,0.0,1.0,NaN,0.0,47.4783,8.36439,...,801010000.0,1.55,7.31186,0.0,6.0,1.0,0.0,0.0,0.008916,0.008932
2016-01-11 16:45:00,0.025582,1.13222,1138.33,1005.40,0.0,1.0,NaN,0.0,47.4783,8.36439,...,800010000.0,0.10,8.96945,1.0,7.0,1.0,0.0,0.0,-0.024976,-0.025218
2016-01-11 17:15:00,0.025625,1.13030,1136.42,1005.41,0.0,1.0,NaN,0.0,47.4783,8.36439,...,800010000.0,0.80,7.41958,0.0,9.0,1.0,0.0,0.0,-0.000850,-0.000857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-09-30 22:45:00,0.026234,1.10322,1117.43,1012.88,0.0,1.0,-0.957786,0.0,47.4783,8.36439,...,800000001.0,0.00,11.26300,135.0,114.0,6.0,0.0,0.0,5.071090,4.745320
2026-09-30 23:15:00,0.026184,1.10528,1119.73,1013.07,0.0,1.0,-2.708120,0.0,47.4783,8.36439,...,800000000.0,0.00,9.37124,40.0,10.0,1.0,0.0,0.0,0.135853,0.133398
2026-09-30 23:45:00,0.026189,1.10510,1119.42,1012.96,0.0,1.0,-1.370940,0.0,47.4783,8.36439,...,800000000.0,0.00,12.06760,48.0,22.0,2.0,0.0,0.0,0.228422,0.218843
2026-10-01 00:15:00,0.026180,1.10548,1119.71,1012.87,0.0,1.0,1.407660,0.0,47.4783,8.36439,...,800000000.0,0.00,9.18256,77.0,1.0,1.0,0.0,0.0,0.103651,0.108589
2026-10-01 00:45:00,0.026172,1.10583,1120.00,1012.81,0.0,1.0,1.226080,0.0,47.4783,8.36439,...,800000000.0,0.00,8.53702,22.0,13.0,1.0,0.0,0.0,0.118156,0.124528

In [3]:
col = 'WD'
wd = df[col].copy()

# Last year in the analysis. A run can reach a few half-hours into the next January, which would
# then enter as a year of its own with almost no records. 2026 covers January to September only.
LASTYEAR = 2026

# The reference year the yearly offsets are measured against is deliberately left at 2024, the year
# it was when this was last run: moving it would change every year's offset and make the results
# incomparable with the previous run, rather than adding a year to them.
REFYEARS = [2024]

# Prepare input data
wd = wd.loc[wd.index.year <= LASTYEAR]
wd = wd.dropna()

wds = WindDirOffset(winddir=wd, offset_start=-50, offset_end=50, hist_ref_years=REFYEARS, hist_n_bins=360)
yearlyoffsets_df = wds.get_yearly_offsets()
print(yearlyoffsets_df)
print(wd)
# HeatmapDateTime(series=wd).show()

# s_corrected = wds.get_corrected_wind_directions()
# print(s_corrected)
# HeatmapDateTime(series=s_corrected).show()

      YEAR  OFFSET
0   2016.0    -2.0
1   2017.0    -3.0
2   2018.0     1.0
3   2019.0     0.0
4   2020.0     1.0
5   2021.0     2.0
6   2022.0     1.0
7   2023.0     2.0
8   2024.0     0.0
9   2025.0     1.0
10  2026.0     2.0
TIMESTAMP_MIDDLE
2016-01-11 15:45:00    241.971
2016-01-11 16:15:00    255.937
2016-01-11 16:45:00    253.310
2016-01-11 17:15:00    248.199
2016-01-11 18:15:00    243.642
                        ...
2026-09-30 22:45:00    279.677
2026-09-30 23:15:00    280.458
2026-09-30 23:45:00    275.129
2026-10-01 00:15:00    268.929
2026-10-01 00:45:00    264.123
Name: WD, Length: 179552, dtype: float64

In [4]:
yearlyoffsets_df

      YEAR  OFFSET
0   2016.0    -2.0
1   2017.0    -3.0
2   2018.0     1.0
3   2019.0     0.0
4   2020.0     1.0
5   2021.0     2.0
6   2022.0     1.0
7   2023.0     2.0
8   2024.0     0.0
9   2025.0     1.0
10  2026.0     2.0

# End of notebook.

In [5]:
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2026-10-22 13:03:29