# Merge IRGA75 (no self-heating correction) with IRGA72 data (2016-2017)
- NEE is prepared for the correction from parallel measurements.
- LE is also added to this correction dataset, but it was not corrected because IRGA75 LE was consistently higher than IRGA72 LE, but the self-heating correction can only *ADD* flux, not reduce it.

In [1]:
from datetime import datetime
import pandas as pd
from diive.core.io.files import save_parquet, load_parquet

# Required variables

In [2]:
# Variable names in EddyPro _fluxnet_ output files
AIR_CP = "AIR_CP"
AIR_DENSITY = "AIR_DENSITY"
VAPOR_DENSITY = "VAPOR_DENSITY"
U = "U"
USTAR = "USTAR"
TA = "TA_T1_47_1_gfXG"
RH = "RH_T1_47_1"
SWIN = "SW_IN_T1_47_1_gfXG"
CO2_MOLAR_DENSITY = "CO2_MOLAR_DENSITY"
H2O_MOLAR_DENSITY = "H2O_MOLAR_DENSITY"
NEE = "NEE_L3.1_L3.2_QCF"
LE = "LE_L3.1_L3.2_QCF"

# Load IRGA75 data

In [3]:
df_nee_irga75 = load_parquet(filepath="02_IRGA75_FluxProcessingChain_after-L3.2_NEE_QCF10_2016-2017.parquet")
df_nee_irga75 = df_nee_irga75[[NEE, CO2_MOLAR_DENSITY]].copy()
df_le_irga75 = load_parquet(filepath="04_IRGA75_FluxProcessingChain_after-L3.2_LE_QCF11_2016-2017.parquet")
df_le_irga75 = df_le_irga75[[LE, H2O_MOLAR_DENSITY]].copy()
df_irga75 = pd.concat([df_nee_irga75, df_le_irga75], axis=1)
df_irga75 = df_irga75.add_suffix('_IRGA75')
df_irga75.describe()
# [print(c) for c in df_nee_irga75 if "RH" in c];

Loaded .parquet file 02_IRGA75_FluxProcessingChain_after-L3.2_NEE_QCF10_2016-2017.parquet (0.442 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file 04_IRGA75_FluxProcessingChain_after-L3.2_LE_QCF11_2016-2017.parquet (0.072 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

       NEE_L3.1_L3.2_QCF_IRGA75  CO2_MOLAR_DENSITY_IRGA75  LE_L3.1_L3.2_QCF_IRGA75  H2O_MOLAR_DENSITY_IRGA75
count              14168.000000              31180.000000             19782.000000              28980.000000
mean                  -6.966600                 16.537655                81.936659                442.406293
std                   11.114344                  2.240562               120.552000                177.441023
min                  -48.713570                  8.497130               -49.981648                 15.802000
25%                  -13.615812                 15.344950                 5.416317                289.206750
50%                   -4.532330                 16.026400                28.811950                412.524000
75%                    0.712564                 16.810625               114.316033                579.911250
max                   29.506870                 34.866200               859.062300                998.288000

# Load IRGA72 data

In [4]:
df_nee_irga72 = load_parquet(filepath="12_IRGA72_FluxProcessingChain_after-L3.2_NEE_QCF10_2016-2017.parquet")
df_nee_irga72 = df_nee_irga72[[NEE, CO2_MOLAR_DENSITY, AIR_CP, AIR_DENSITY, VAPOR_DENSITY, U, USTAR, TA, SWIN, RH]].copy()

df_le_irga72 = load_parquet(filepath="14_IRGA72_FluxProcessingChain_after-L3.2_LE_QCF11_2016-2017.parquet")
df_le_irga72 = df_le_irga72[[LE, H2O_MOLAR_DENSITY]].copy()

df_irga72 = pd.concat([df_nee_irga72, df_le_irga72], axis=1)
df_irga72 = df_irga72.add_suffix('_IRGA72')
df_irga72.describe()

Loaded .parquet file 12_IRGA72_FluxProcessingChain_after-L3.2_NEE_QCF10_2016-2017.parquet (0.064 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file 14_IRGA72_FluxProcessingChain_after-L3.2_LE_QCF11_2016-2017.parquet (0.064 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

       NEE_L3.1_L3.2_QCF_IRGA72  CO2_MOLAR_DENSITY_IRGA72  AIR_CP_IRGA72  AIR_DENSITY_IRGA72  VAPOR_DENSITY_IRGA72      U_IRGA72  USTAR_IRGA72  TA_T1_47_1_gfXG_IRGA72  SW_IN_T1_47_1_gfXG_IRGA72  RH_T1_47_1_IRGA72  LE_L3.1_L3.2_QCF_IRGA72  H2O_MOLAR_DENSITY_IRGA72
count              13738.000000              27474.000000   27749.000000        27749.000000          27749.000000  27749.000000  27749.000000            28032.000000               28032.000000       28028.000000             18409.000000              27144.000000
mean                  -4.106021                 15.574433    1011.736249            1.141921              0.008234      2.447515      0.465091               10.725810                 155.227218          80.873202                74.338471                455.794507
std                   10.552376                  1.154616       2.845976            0.037616              0.003242      1.715387      0.296126                8.527703                 250.942361          18.363838               120.159677                178.755212
min                  -49.982370                  8.152490    1006.370000            1.058090              0.001956      0.009557      0.009705              -12.170839                   0.000000          22.011724               -49.954200                106.438000
25%                   -9.708519                 14.935025    1009.250000            1.113530              0.005374      1.171170      0.238995                3.862654                   0.000000          66.794079                 0.741355                299.610000
50%                   -1.054724                 15.581750    1011.450000            1.137810              0.007969      2.076520      0.406357               11.298311                   0.000000          84.752255                17.503750                442.887500
75%                    2.620790                 16.237800    1013.950000            1.168630              0.010792      3.316100      0.625380               17.193330                 219.860125          99.526525               103.658890                597.078500
max                   38.419780                 28.265000    1020.570000            1.259900              0.017989     11.932600      2.898660               32.604572                1110.706662          99.864659               740.762170                987.199000

# Merge data

In [5]:
df = pd.concat([df_irga72, df_irga75], axis=1)
df.describe()

       NEE_L3.1_L3.2_QCF_IRGA72  CO2_MOLAR_DENSITY_IRGA72  AIR_CP_IRGA72  AIR_DENSITY_IRGA72  VAPOR_DENSITY_IRGA72      U_IRGA72  USTAR_IRGA72  TA_T1_47_1_gfXG_IRGA72  SW_IN_T1_47_1_gfXG_IRGA72  RH_T1_47_1_IRGA72  LE_L3.1_L3.2_QCF_IRGA72  H2O_MOLAR_DENSITY_IRGA72  NEE_L3.1_L3.2_QCF_IRGA75  CO2_MOLAR_DENSITY_IRGA75  LE_L3.1_L3.2_QCF_IRGA75  H2O_MOLAR_DENSITY_IRGA75
count              13738.000000              27474.000000   27749.000000        27749.000000          27749.000000  27749.000000  27749.000000            28032.000000               28032.000000       28028.000000             18409.000000              27144.000000              14168.000000              31180.000000             19782.000000              28980.000000
mean                  -4.106021                 15.574433    1011.736249            1.141921              0.008234      2.447515      0.465091               10.725810                 155.227218          80.873202                74.338471                455.794507                 -6.966600                 16.537655                81.936659                442.406293
std                   10.552376                  1.154616       2.845976            0.037616              0.003242      1.715387      0.296126                8.527703                 250.942361          18.363838               120.159677                178.755212                 11.114344                  2.240562               120.552000                177.441023
min                  -49.982370                  8.152490    1006.370000            1.058090              0.001956      0.009557      0.009705              -12.170839                   0.000000          22.011724               -49.954200                106.438000                -48.713570                  8.497130               -49.981648                 15.802000
25%                   -9.708519                 14.935025    1009.250000            1.113530              0.005374      1.171170      0.238995                3.862654                   0.000000          66.794079                 0.741355                299.610000                -13.615812                 15.344950                 5.416317                289.206750
50%                   -1.054724                 15.581750    1011.450000            1.137810              0.007969      2.076520      0.406357               11.298311                   0.000000          84.752255                17.503750                442.887500                 -4.532330                 16.026400                28.811950                412.524000
75%                    2.620790                 16.237800    1013.950000            1.168630              0.010792      3.316100      0.625380               17.193330                 219.860125          99.526525               103.658890                597.078500                  0.712564                 16.810625               114.316033                579.911250
max                   38.419780                 28.265000    1020.570000            1.259900              0.017989     11.932600      2.898660               32.604572                1110.706662          99.864659               740.762170                987.199000                 29.506870                 34.866200               859.062300                998.288000

# Save to file

In [6]:
filename = "22_MERGED_IRGA75-noSHC+IRGA72_FluxProcessingChain_after-L3.2_NEE-QCF10_LE-QCF11_2016-2017"
df.to_csv(f"{filename}.csv", index=True)
save_parquet(data=df, filename=filename)

Saved file 22_MERGED_IRGA75-noSHC+IRGA72_FluxProcessingChain_after-L3.2_NEE-QCF10_LE-QCF11_2016-2017.parquet (0.037 seconds).

'22_MERGED_IRGA75-noSHC+IRGA72_FluxProcessingChain_after-L3.2_NEE-QCF10_LE-QCF11_2016-2017.parquet'

# ✅END OF NOTEBOOK

In [7]:
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2025-11-28 15:40:15