# Merge IRGA75 (no self-heating correction) with IRGA72 data (2016-2017)

In [1]:
from datetime import datetime
import pandas as pd
from diive.core.io.files import save_parquet, load_parquet

# Required variables

In [5]:
# Variable names in EddyPro _fluxnet_ output files
AIR_CP = "AIR_CP"
AIR_DENSITY = "AIR_DENSITY"
VAPOR_DENSITY = "VAPOR_DENSITY"
U = "U"
USTAR = "USTAR"
TA = "TA_T1_47_1_gfXG"
SWIN = "SW_IN_T1_47_1_gfXG"
CO2_MOLAR_DENSITY = "CO2_MOLAR_DENSITY"
FLUX = "NEE_L3.1_L3.2_QCF"

usecols_irga75 = [FLUX, CO2_MOLAR_DENSITY]
usecols_irga72 = [FLUX, AIR_CP, AIR_DENSITY, VAPOR_DENSITY, U, USTAR, TA, SWIN, CO2_MOLAR_DENSITY]

# Load IRGA75 data

In [6]:
df_irga75 = load_parquet(filepath="02_IRGA75_FluxProcessingChain_after-L3.2_NEE_QCF10_2016-2017.parquet")
# [print(c) for c in df_irga75 if "NEE" in c];

Loaded .parquet file 02_IRGA75_FluxProcessingChain_after-L3.2_NEE_QCF10_2016-2017.parquet (0.067 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

In [7]:
df_irga75 = df_irga75[usecols_irga75].copy()
df_irga75 = df_irga75.add_suffix('_IRGA75')
df_irga75.describe()

       NEE_L3.1_L3.2_QCF_IRGA75  CO2_MOLAR_DENSITY_IRGA75
count              14168.000000              31180.000000
mean                  -6.966600                 16.537655
std                   11.114344                  2.240562
min                  -48.713570                  8.497130
25%                  -13.615812                 15.344950
50%                   -4.532330                 16.026400
75%                    0.712564                 16.810625
max                   29.506870                 34.866200

# Load IRGA72 data

In [9]:
df_irga72 = load_parquet(filepath="12_IRGA72_FluxProcessingChain_after-L3.2_NEE_QCF10_2016-2017.parquet")

Loaded .parquet file 12_IRGA72_FluxProcessingChain_after-L3.2_NEE_QCF10_2016-2017.parquet (0.056 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

In [10]:
df_irga72 = df_irga72[usecols_irga72].copy()
df_irga72 = df_irga72.add_suffix('_IRGA72')
df_irga72.describe()

       NEE_L3.1_L3.2_QCF_IRGA72  AIR_CP_IRGA72  AIR_DENSITY_IRGA72  VAPOR_DENSITY_IRGA72      U_IRGA72  USTAR_IRGA72  TA_T1_47_1_gfXG_IRGA72  SW_IN_T1_47_1_gfXG_IRGA72  CO2_MOLAR_DENSITY_IRGA72
count              13738.000000   27749.000000        27749.000000          27749.000000  27749.000000  27749.000000            28032.000000               28032.000000              27474.000000
mean                  -4.106021    1011.736249            1.141921              0.008234      2.447515      0.465091               10.725810                 155.227218                 15.574433
std                   10.552376       2.845976            0.037616              0.003242      1.715387      0.296126                8.527703                 250.942361                  1.154616
min                  -49.982370    1006.370000            1.058090              0.001956      0.009557      0.009705              -12.170839                   0.000000                  8.152490
25%                   -9.708519    1009.250000            1.113530              0.005374      1.171170      0.238995                3.862654                   0.000000                 14.935025
50%                   -1.054724    1011.450000            1.137810              0.007969      2.076520      0.406357               11.298311                   0.000000                 15.581750
75%                    2.620790    1013.950000            1.168630              0.010792      3.316100      0.625380               17.193330                 219.860125                 16.237800
max                   38.419780    1020.570000            1.259900              0.017989     11.932600      2.898660               32.604572                1110.706662                 28.265000

# Merge data

In [11]:
df = pd.concat([df_irga72, df_irga75], axis=1)
df.describe()

       NEE_L3.1_L3.2_QCF_IRGA72  AIR_CP_IRGA72  AIR_DENSITY_IRGA72  VAPOR_DENSITY_IRGA72      U_IRGA72  USTAR_IRGA72  TA_T1_47_1_gfXG_IRGA72  SW_IN_T1_47_1_gfXG_IRGA72  CO2_MOLAR_DENSITY_IRGA72  NEE_L3.1_L3.2_QCF_IRGA75  CO2_MOLAR_DENSITY_IRGA75
count              13738.000000   27749.000000        27749.000000          27749.000000  27749.000000  27749.000000            28032.000000               28032.000000              27474.000000              14168.000000              31180.000000
mean                  -4.106021    1011.736249            1.141921              0.008234      2.447515      0.465091               10.725810                 155.227218                 15.574433                 -6.966600                 16.537655
std                   10.552376       2.845976            0.037616              0.003242      1.715387      0.296126                8.527703                 250.942361                  1.154616                 11.114344                  2.240562
min                  -49.982370    1006.370000            1.058090              0.001956      0.009557      0.009705              -12.170839                   0.000000                  8.152490                -48.713570                  8.497130
25%                   -9.708519    1009.250000            1.113530              0.005374      1.171170      0.238995                3.862654                   0.000000                 14.935025                -13.615812                 15.344950
50%                   -1.054724    1011.450000            1.137810              0.007969      2.076520      0.406357               11.298311                   0.000000                 15.581750                 -4.532330                 16.026400
75%                    2.620790    1013.950000            1.168630              0.010792      3.316100      0.625380               17.193330                 219.860125                 16.237800                  0.712564                 16.810625
max                   38.419780    1020.570000            1.259900              0.017989     11.932600      2.898660               32.604572                1110.706662                 28.265000                 29.506870                 34.866200

# Save to file

In [12]:
filename = "21_MERGED_IRGA75-noSHC+IRGA72_FluxProcessingChain_after-L3.2_NEE_QCF10_2016-2017"
df.to_csv(f"{filename}.csv", index=True)
save_parquet(data=df, filename=filename)

Saved file 21_MERGED_IRGA75-noSHC+IRGA72_FluxProcessingChain_after-L3.2_NEE_QCF10_2016-2017.parquet (0.026 seconds).

'21_MERGED_IRGA75-noSHC+IRGA72_FluxProcessingChain_after-L3.2_NEE_QCF10_2016-2017.parquet'

# ✅END OF NOTEBOOK

In [13]:
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2025-11-22 14:07:24